// Code generated by MockGen. DO NOT EDIT.
// Source: solana.go
//
// Generated by this command:
//
//	mockgen -source=solana.go -destination=mocks/solana_mock.go -package=solMocks
//

// Package solMocks is a generated GoMock package.
package solMocks

import (
	context "context"
	solanarpc "mm/internal/client/solanarpc"
	reflect "reflect"

	solana "github.com/gagliardetto/solana-go"
	gomock "go.uber.org/mock/gomock"
)

// MockSolanaRPC is a mock of SolanaRPC interface.
type MockSolanaRPC struct {
	ctrl     *gomock.Controller
	recorder *MockSolanaRPCMockRecorder
	isgomock struct{}
}

// MockSolanaRPCMockRecorder is the mock recorder for MockSolanaRPC.
type MockSolanaRPCMockRecorder struct {
	mock *MockSolanaRPC
}

// NewMockSolanaRPC creates a new mock instance.
func NewMockSolanaRPC(ctrl *gomock.Controller) *MockSolanaRPC {
	mock := &MockSolanaRPC{ctrl: ctrl}
	mock.recorder = &MockSolanaRPCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolanaRPC) EXPECT() *MockSolanaRPCMockRecorder {
	return m.recorder
}

// GetWalletBalance mocks base method.
func (m *MockSolanaRPC) GetWalletBalance(ctx context.Context, wallets solana.PublicKey) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletBalance", ctx, wallets)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletBalance indicates an expected call of GetWalletBalance.
func (mr *MockSolanaRPCMockRecorder) GetWalletBalance(ctx, wallets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletBalance", reflect.TypeOf((*MockSolanaRPC)(nil).GetWalletBalance), ctx, wallets)
}

// GetATARentExemption mocks base method.
func (m *MockSolanaRPC) GetATARentExemption(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetATARentExemption", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetATARentExemption indicates an expected call of GetATARentExemption.
func (mr *MockSolanaRPCMockRecorder) GetATARentExemption(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetATARentExemption", reflect.TypeOf((*MockSolanaRPC)(nil).GetATARentExemption), ctx)
}

// GetRentExemption mocks base method.
func (m *MockSolanaRPC) GetRentExemption(ctx context.Context, size uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRentExemption", ctx, size)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRentExemption indicates an expected call of GetRentExemption.
func (mr *MockSolanaRPCMockRecorder) GetRentExemption(ctx, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRentExemption", reflect.TypeOf((*MockSolanaRPC)(nil).GetRentExemption), ctx, size)
}

// GetWalletTransactions mocks base method.
func (m *MockSolanaRPC) GetWalletTransactions(ctx context.Context, req *solanarpc.GetTransactionsReq) ([]solanarpc.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletTransactions", ctx, req)
	ret0, _ := ret[0].([]solanarpc.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletTransactions indicates an expected call of GetWalletTransactions.
func (mr *MockSolanaRPCMockRecorder) GetWalletTransactions(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletTransactions", reflect.TypeOf((*MockSolanaRPC)(nil).GetWalletTransactions), ctx, req)
}
