// Code generated by MockGen. DO NOT EDIT.
// Source: kucoin.go
//
// Generated by this command:
//
//	mockgen -source=kucoin.go -destination=mocks/kucoin_mock.go -package=kcMocks
//

// Package kcMocks is a generated GoMock package.
package kcMocks

import (
	context "context"
	kucoinapi "mm/internal/client/kucoinapi"
	model "mm/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKuCoinApi is a mock of KuCoinApi interface.
type MockKuCoinApi struct {
	ctrl     *gomock.Controller
	recorder *MockKuCoinApiMockRecorder
	isgomock struct{}
}

// MockKuCoinApiMockRecorder is the mock recorder for MockKuCoinApi.
type MockKuCoinApiMockRecorder struct {
	mock *MockKuCoinApi
}

// NewMockKuCoinApi creates a new mock instance.
func NewMockKuCoinApi(ctrl *gomock.Controller) *MockKuCoinApi {
	mock := &MockKuCoinApi{ctrl: ctrl}
	mock.recorder = &MockKuCoinApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKuCoinApi) EXPECT() *MockKuCoinApiMockRecorder {
	return m.recorder
}

// GetKeyInfo mocks base method.
func (m *MockKuCoinApi) GetKeyInfo(ctx context.Context, key *model.Key) (*kucoinapi.KeyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyInfo", ctx, key)
	ret0, _ := ret[0].(*kucoinapi.KeyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyInfo indicates an expected call of GetKeyInfo.
func (mr *MockKuCoinApiMockRecorder) GetKeyInfo(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyInfo", reflect.TypeOf((*MockKuCoinApi)(nil).GetKeyInfo), ctx, key)
}

// GetSolBalance mocks base method.
func (m *MockKuCoinApi) GetSolBalance(ctx context.Context, acc *model.Account) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSolBalance", ctx, acc)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSolBalance indicates an expected call of GetSolBalance.
func (mr *MockKuCoinApiMockRecorder) GetSolBalance(ctx, acc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSolBalance", reflect.TypeOf((*MockKuCoinApi)(nil).GetSolBalance), ctx, acc)
}

// GetSolWithdrawDetails mocks base method.
func (m *MockKuCoinApi) GetSolWithdrawDetails(ctx context.Context, key *model.Key) (*kucoinapi.WithdrawQuotas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSolWithdrawDetails", ctx, key)
	ret0, _ := ret[0].(*kucoinapi.WithdrawQuotas)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSolWithdrawDetails indicates an expected call of GetSolWithdrawDetails.
func (mr *MockKuCoinApiMockRecorder) GetSolWithdrawDetails(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSolWithdrawDetails", reflect.TypeOf((*MockKuCoinApi)(nil).GetSolWithdrawDetails), ctx, key)
}

// GetWithdrawalStatus mocks base method.
func (m *MockKuCoinApi) GetWithdrawalStatus(ctx context.Context, key *model.Key, withdrawalID string) (*kucoinapi.WithdrawalStatusResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalStatus", ctx, key, withdrawalID)
	ret0, _ := ret[0].(*kucoinapi.WithdrawalStatusResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalStatus indicates an expected call of GetWithdrawalStatus.
func (mr *MockKuCoinApiMockRecorder) GetWithdrawalStatus(ctx, key, withdrawalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalStatus", reflect.TypeOf((*MockKuCoinApi)(nil).GetWithdrawalStatus), ctx, key, withdrawalID)
}

// Withdraw mocks base method.
func (m *MockKuCoinApi) Withdraw(ctx context.Context, key *model.Key, req *kucoinapi.WithdrawReq) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, key, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockKuCoinApiMockRecorder) Withdraw(ctx, key, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockKuCoinApi)(nil).Withdraw), ctx, key, req)
}
