// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package openbook_v2

import (
	"fmt"

	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_Market:
		value := new(Market)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Market: %w", err)
		}
		return value, nil
	case Account_OpenOrdersAccount:
		value := new(OpenOrdersAccount)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as OpenOrdersAccount: %w", err)
		}
		return value, nil
	case Account_OpenOrdersIndexer:
		value := new(OpenOrdersIndexer)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as OpenOrdersIndexer: %w", err)
		}
		return value, nil
	case Account_StubOracle:
		value := new(StubOracle)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as StubOracle: %w", err)
		}
		return value, nil
	case Account_BookSide:
		value := new(BookSide)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as BookSide: %w", err)
		}
		return value, nil
	case Account_EventHeap:
		value := new(EventHeap)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as EventHeap: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_Market(accountData []byte) (*Market, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Market {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Market, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Market)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Market: %w", err)
	}
	return acc, nil
}

func ParseAccount_OpenOrdersAccount(accountData []byte) (*OpenOrdersAccount, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_OpenOrdersAccount {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_OpenOrdersAccount, binary.FormatDiscriminator(discriminator))
	}
	acc := new(OpenOrdersAccount)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type OpenOrdersAccount: %w", err)
	}
	return acc, nil
}

func ParseAccount_OpenOrdersIndexer(accountData []byte) (*OpenOrdersIndexer, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_OpenOrdersIndexer {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_OpenOrdersIndexer, binary.FormatDiscriminator(discriminator))
	}
	acc := new(OpenOrdersIndexer)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type OpenOrdersIndexer: %w", err)
	}
	return acc, nil
}

func ParseAccount_StubOracle(accountData []byte) (*StubOracle, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_StubOracle {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_StubOracle, binary.FormatDiscriminator(discriminator))
	}
	acc := new(StubOracle)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type StubOracle: %w", err)
	}
	return acc, nil
}

func ParseAccount_BookSide(accountData []byte) (*BookSide, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_BookSide {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_BookSide, binary.FormatDiscriminator(discriminator))
	}
	acc := new(BookSide)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type BookSide: %w", err)
	}
	return acc, nil
}

func ParseAccount_EventHeap(accountData []byte) (*EventHeap, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_EventHeap {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_EventHeap, binary.FormatDiscriminator(discriminator))
	}
	acc := new(EventHeap)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type EventHeap: %w", err)
	}
	return acc, nil
}
