// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package openbook_v2

// Account discriminators
var (
	Account_Market            = [8]byte{219, 190, 213, 55, 0, 227, 198, 154}
	Account_OpenOrdersAccount = [8]byte{255, 194, 78, 123, 16, 105, 208, 165}
	Account_OpenOrdersIndexer = [8]byte{195, 83, 128, 213, 204, 91, 19, 150}
	Account_StubOracle        = [8]byte{224, 251, 254, 99, 177, 174, 137, 4}
	Account_BookSide          = [8]byte{72, 44, 225, 141, 178, 130, 97, 57}
	Account_EventHeap         = [8]byte{119, 59, 61, 19, 165, 84, 57, 175}
)

// Event discriminators
var (
	Event_DepositLog            = [8]byte{141, 186, 168, 252, 108, 141, 72, 94}
	Event_FillLog               = [8]byte{150, 23, 41, 148, 152, 162, 215, 64}
	Event_MarketMetaDataLog     = [8]byte{209, 87, 212, 236, 164, 58, 60, 117}
	Event_TotalOrderFillEvent   = [8]byte{8, 235, 48, 58, 174, 76, 156, 105}
	Event_SetDelegateLog        = [8]byte{53, 130, 151, 92, 109, 57, 145, 112}
	Event_SettleFundsLog        = [8]byte{10, 50, 240, 117, 237, 67, 230, 233}
	Event_SweepFeesLog          = [8]byte{210, 242, 26, 77, 94, 48, 255, 61}
	Event_OpenOrdersPositionLog = [8]byte{196, 249, 148, 33, 168, 228, 73, 6}
)

// Instruction discriminators
var (
	Instruction_CreateMarket               = [8]byte{103, 226, 97, 235, 200, 188, 251, 254}
	Instruction_CloseMarket                = [8]byte{88, 154, 248, 186, 48, 14, 123, 244}
	Instruction_CreateOpenOrdersIndexer    = [8]byte{64, 64, 153, 255, 217, 71, 249, 133}
	Instruction_CloseOpenOrdersIndexer     = [8]byte{103, 249, 229, 231, 247, 253, 197, 136}
	Instruction_CreateOpenOrdersAccount    = [8]byte{204, 181, 175, 222, 40, 125, 188, 71}
	Instruction_CloseOpenOrdersAccount     = [8]byte{176, 74, 115, 210, 54, 179, 91, 103}
	Instruction_PlaceOrder                 = [8]byte{51, 194, 155, 175, 109, 130, 96, 106}
	Instruction_EditOrder                  = [8]byte{254, 208, 118, 29, 173, 248, 200, 70}
	Instruction_EditOrderPegged            = [8]byte{62, 187, 125, 69, 26, 221, 157, 133}
	Instruction_PlaceOrders                = [8]byte{60, 63, 50, 123, 12, 197, 60, 190}
	Instruction_CancelAllAndPlaceOrders    = [8]byte{128, 155, 222, 60, 186, 40, 225, 50}
	Instruction_PlaceOrderPegged           = [8]byte{141, 185, 251, 63, 74, 85, 210, 145}
	Instruction_PlaceTakeOrder             = [8]byte{3, 44, 71, 3, 26, 199, 203, 85}
	Instruction_ConsumeEvents              = [8]byte{221, 145, 177, 52, 31, 47, 63, 201}
	Instruction_ConsumeGivenEvents         = [8]byte{209, 227, 54, 4, 109, 172, 41, 71}
	Instruction_CancelOrder                = [8]byte{95, 129, 237, 240, 8, 49, 223, 132}
	Instruction_CancelOrderByClientOrderId = [8]byte{115, 178, 201, 8, 175, 183, 123, 119}
	Instruction_CancelAllOrders            = [8]byte{196, 83, 243, 171, 17, 100, 160, 143}
	Instruction_Deposit                    = [8]byte{242, 35, 198, 137, 82, 225, 242, 182}
	Instruction_Refill                     = [8]byte{128, 207, 142, 11, 54, 232, 38, 201}
	Instruction_SettleFunds                = [8]byte{238, 64, 163, 96, 75, 171, 16, 33}
	Instruction_SettleFundsExpired         = [8]byte{107, 18, 56, 69, 228, 56, 55, 164}
	Instruction_SweepFees                  = [8]byte{175, 225, 98, 71, 118, 66, 34, 148}
	Instruction_SetDelegate                = [8]byte{242, 30, 46, 76, 108, 235, 128, 181}
	Instruction_SetMarketExpired           = [8]byte{219, 82, 219, 236, 60, 115, 197, 64}
	Instruction_PruneOrders                = [8]byte{27, 213, 159, 191, 12, 116, 112, 121}
	Instruction_StubOracleCreate           = [8]byte{172, 63, 101, 83, 141, 76, 199, 216}
	Instruction_StubOracleClose            = [8]byte{92, 137, 45, 3, 45, 60, 117, 224}
	Instruction_StubOracleSet              = [8]byte{109, 198, 79, 121, 65, 202, 161, 142}
)
