// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package openbook_v2

import (
	"fmt"

	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_DepositLog:
		value := new(DepositLog)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as DepositLog: %w", err)
		}
		return value, nil
	case Event_FillLog:
		value := new(FillLog)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as FillLog: %w", err)
		}
		return value, nil
	case Event_MarketMetaDataLog:
		value := new(MarketMetaDataLog)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as MarketMetaDataLog: %w", err)
		}
		return value, nil
	case Event_TotalOrderFillEvent:
		value := new(TotalOrderFillEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as TotalOrderFillEvent: %w", err)
		}
		return value, nil
	case Event_SetDelegateLog:
		value := new(SetDelegateLog)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SetDelegateLog: %w", err)
		}
		return value, nil
	case Event_SettleFundsLog:
		value := new(SettleFundsLog)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SettleFundsLog: %w", err)
		}
		return value, nil
	case Event_SweepFeesLog:
		value := new(SweepFeesLog)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SweepFeesLog: %w", err)
		}
		return value, nil
	case Event_OpenOrdersPositionLog:
		value := new(OpenOrdersPositionLog)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as OpenOrdersPositionLog: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_DepositLog(eventData []byte) (*DepositLog, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_DepositLog {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_DepositLog, binary.FormatDiscriminator(discriminator))
	}
	event := new(DepositLog)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type DepositLog: %w", err)
	}
	return event, nil
}

func ParseEvent_FillLog(eventData []byte) (*FillLog, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_FillLog {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_FillLog, binary.FormatDiscriminator(discriminator))
	}
	event := new(FillLog)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type FillLog: %w", err)
	}
	return event, nil
}

func ParseEvent_MarketMetaDataLog(eventData []byte) (*MarketMetaDataLog, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_MarketMetaDataLog {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_MarketMetaDataLog, binary.FormatDiscriminator(discriminator))
	}
	event := new(MarketMetaDataLog)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type MarketMetaDataLog: %w", err)
	}
	return event, nil
}

func ParseEvent_TotalOrderFillEvent(eventData []byte) (*TotalOrderFillEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_TotalOrderFillEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_TotalOrderFillEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(TotalOrderFillEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type TotalOrderFillEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SetDelegateLog(eventData []byte) (*SetDelegateLog, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SetDelegateLog {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SetDelegateLog, binary.FormatDiscriminator(discriminator))
	}
	event := new(SetDelegateLog)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SetDelegateLog: %w", err)
	}
	return event, nil
}

func ParseEvent_SettleFundsLog(eventData []byte) (*SettleFundsLog, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SettleFundsLog {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SettleFundsLog, binary.FormatDiscriminator(discriminator))
	}
	event := new(SettleFundsLog)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SettleFundsLog: %w", err)
	}
	return event, nil
}

func ParseEvent_SweepFeesLog(eventData []byte) (*SweepFeesLog, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SweepFeesLog {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SweepFeesLog, binary.FormatDiscriminator(discriminator))
	}
	event := new(SweepFeesLog)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SweepFeesLog: %w", err)
	}
	return event, nil
}

func ParseEvent_OpenOrdersPositionLog(eventData []byte) (*OpenOrdersPositionLog, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_OpenOrdersPositionLog {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_OpenOrdersPositionLog, binary.FormatDiscriminator(discriminator))
	}
	event := new(OpenOrdersPositionLog)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type OpenOrdersPositionLog: %w", err)
	}
	return event, nil
}
