// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package openbook_v2

import (
	"bytes"
	"fmt"

	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "create_market" instruction.
// Create a [`Market`](crate::state::Market) for a given token pair.
func NewCreateMarketInstruction(
	// Params:
	nameParam string,
	oracleConfigParam OracleConfigParams,
	quoteLotSizeParam int64,
	baseLotSizeParam int64,
	makerFeeParam int64,
	takerFeeParam int64,
	timeExpiryParam int64,

	// Accounts:
	marketAccount solanago.PublicKey,
	marketAuthorityAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
	payerAccount solanago.PublicKey,
	marketBaseVaultAccount solanago.PublicKey,
	marketQuoteVaultAccount solanago.PublicKey,
	baseMintAccount solanago.PublicKey,
	quoteMintAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	oracleAAccount solanago.PublicKey,
	oracleBAccount solanago.PublicKey,
	collectFeeAdminAccount solanago.PublicKey,
	openOrdersAdminAccount solanago.PublicKey,
	consumeEventsAdminAccount solanago.PublicKey,
	closeMarketAdminAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CreateMarket[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `nameParam`:
		err = enc__.Encode(nameParam)
		if err != nil {
			return nil, errors.NewField("nameParam", err)
		}
		// Serialize `oracleConfigParam`:
		err = enc__.Encode(oracleConfigParam)
		if err != nil {
			return nil, errors.NewField("oracleConfigParam", err)
		}
		// Serialize `quoteLotSizeParam`:
		err = enc__.Encode(quoteLotSizeParam)
		if err != nil {
			return nil, errors.NewField("quoteLotSizeParam", err)
		}
		// Serialize `baseLotSizeParam`:
		err = enc__.Encode(baseLotSizeParam)
		if err != nil {
			return nil, errors.NewField("baseLotSizeParam", err)
		}
		// Serialize `makerFeeParam`:
		err = enc__.Encode(makerFeeParam)
		if err != nil {
			return nil, errors.NewField("makerFeeParam", err)
		}
		// Serialize `takerFeeParam`:
		err = enc__.Encode(takerFeeParam)
		if err != nil {
			return nil, errors.NewField("takerFeeParam", err)
		}
		// Serialize `timeExpiryParam`:
		err = enc__.Encode(timeExpiryParam)
		if err != nil {
			return nil, errors.NewField("timeExpiryParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "market": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, true))
		// Account 1 "market_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAuthorityAccount, false, false))
		// Account 2 "bids": Writable, Non-signer, Required
		// Accounts are initialized by client,
		// anchor discriminator is set first when ix exits,
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 3 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
		// Account 4 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
		// Account 5 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 6 "market_base_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketBaseVaultAccount, true, false))
		// Account 7 "market_quote_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketQuoteVaultAccount, true, false))
		// Account 8 "base_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(baseMintAccount, false, false))
		// Account 9 "quote_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteMintAccount, false, false))
		// Account 10 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 11 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 12 "associated_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 13 "oracle_a": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleAAccount, false, false))
		// Account 14 "oracle_b": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleBAccount, false, false))
		// Account 15 "collect_fee_admin": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(collectFeeAdminAccount, false, false))
		// Account 16 "open_orders_admin": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(openOrdersAdminAccount, false, false))
		// Account 17 "consume_events_admin": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(consumeEventsAdminAccount, false, false))
		// Account 18 "close_market_admin": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(closeMarketAdminAccount, false, false))
		// Account 19 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 20 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "close_market" instruction.
// Close a [`Market`](crate::state::Market) (only // [`close_market_admin`](crate::state::Market::close_market_admin)).
func NewCloseMarketInstruction(
	closeMarketAdminAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
	solDestinationAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "close_market_admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(closeMarketAdminAccount, false, true))
		// Account 1 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 2 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 3 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
		// Account 4 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
		// Account 5 "sol_destination": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(solDestinationAccount, true, false))
		// Account 6 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "create_open_orders_indexer" instruction.
// Create an [`OpenOrdersIndexer`](crate::state::OpenOrdersIndexer) account.
func NewCreateOpenOrdersIndexerInstruction(
	payerAccount solanago.PublicKey,
	ownerAccount solanago.PublicKey,
	openOrdersIndexerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, true))
		// Account 2 "open_orders_indexer": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersIndexerAccount, true, false))
		// Account 3 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "close_open_orders_indexer" instruction.
// Close an [`OpenOrdersIndexer`](crate::state::OpenOrdersIndexer) account.
func NewCloseOpenOrdersIndexerInstruction(
	ownerAccount solanago.PublicKey,
	openOrdersIndexerAccount solanago.PublicKey,
	solDestinationAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, true))
		// Account 1 "open_orders_indexer": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersIndexerAccount, true, false))
		// Account 2 "sol_destination": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(solDestinationAccount, true, false))
		// Account 3 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "create_open_orders_account" instruction.
// Create an [`OpenOrdersAccount`](crate::state::OpenOrdersAccount).
func NewCreateOpenOrdersAccountInstruction(
	// Params:
	nameParam string,

	// Accounts:
	payerAccount solanago.PublicKey,
	ownerAccount solanago.PublicKey,
	delegateAccountAccount solanago.PublicKey,
	openOrdersIndexerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CreateOpenOrdersAccount[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `nameParam`:
		err = enc__.Encode(nameParam)
		if err != nil {
			return nil, errors.NewField("nameParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, true))
		// Account 2 "delegate_account": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(delegateAccountAccount, false, false))
		// Account 3 "open_orders_indexer": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersIndexerAccount, true, false))
		// Account 4 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 5 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 6 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "close_open_orders_account" instruction.
// Close an [`OpenOrdersAccount`](crate::state::OpenOrdersAccount).
func NewCloseOpenOrdersAccountInstruction(
	ownerAccount solanago.PublicKey,
	openOrdersIndexerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	solDestinationAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, true))
		// Account 1 "open_orders_indexer": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersIndexerAccount, true, false))
		// Account 2 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 3 "sol_destination": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(solDestinationAccount, true, false))
		// Account 4 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "place_order" instruction.
// Place an order. //  // Different types of orders have different effects on the order book, // as described in [`PlaceOrderType`](crate::state::PlaceOrderType). //  // `price_lots` refers to the price in lots: the number of quote lots // per base lot. It is ignored for `PlaceOrderType::Market` orders. //  // `expiry_timestamp` is a unix timestamp for when this order should // expire. If 0 is passed in, the order will never expire. If the time // is in the past, the instruction is skipped. Timestamps in the future // are reduced to now + 65,535s. //  // `limit` determines the maximum number of orders from the book to fill, // and can be used to limit CU spent. When the limit is reached, processing // stops and the instruction succeeds.
func NewPlaceOrderInstruction(
	// Params:
	argsParam PlaceOrderArgs,

	// Accounts:
	signerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	openOrdersAdminAccount solanago.PublicKey,
	userTokenAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
	marketVaultAccount solanago.PublicKey,
	oracleAAccount solanago.PublicKey,
	oracleBAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_PlaceOrder[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "open_orders_admin": Read-only, Signer, Optional
		accounts__.Append(solanago.NewAccountMeta(openOrdersAdminAccount, false, true))
		// Account 3 "user_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAccount, true, false))
		// Account 4 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 5 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 6 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
		// Account 7 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
		// Account 8 "market_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketVaultAccount, true, false))
		// Account 9 "oracle_a": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleAAccount, false, false))
		// Account 10 "oracle_b": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleBAccount, false, false))
		// Account 11 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "edit_order" instruction.
// Edit an order.
func NewEditOrderInstruction(
	// Params:
	clientOrderIdParam uint64,
	expectedCancelSizeParam int64,
	placeOrderParam PlaceOrderArgs,

	// Accounts:
	signerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	openOrdersAdminAccount solanago.PublicKey,
	userTokenAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
	marketVaultAccount solanago.PublicKey,
	oracleAAccount solanago.PublicKey,
	oracleBAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_EditOrder[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `clientOrderIdParam`:
		err = enc__.Encode(clientOrderIdParam)
		if err != nil {
			return nil, errors.NewField("clientOrderIdParam", err)
		}
		// Serialize `expectedCancelSizeParam`:
		err = enc__.Encode(expectedCancelSizeParam)
		if err != nil {
			return nil, errors.NewField("expectedCancelSizeParam", err)
		}
		// Serialize `placeOrderParam`:
		err = enc__.Encode(placeOrderParam)
		if err != nil {
			return nil, errors.NewField("placeOrderParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "open_orders_admin": Read-only, Signer, Optional
		accounts__.Append(solanago.NewAccountMeta(openOrdersAdminAccount, false, true))
		// Account 3 "user_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAccount, true, false))
		// Account 4 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 5 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 6 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
		// Account 7 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
		// Account 8 "market_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketVaultAccount, true, false))
		// Account 9 "oracle_a": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleAAccount, false, false))
		// Account 10 "oracle_b": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleBAccount, false, false))
		// Account 11 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "edit_order_pegged" instruction.
// Edit an order pegged.
func NewEditOrderPeggedInstruction(
	// Params:
	clientOrderIdParam uint64,
	expectedCancelSizeParam int64,
	placeOrderParam PlaceOrderPeggedArgs,

	// Accounts:
	signerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	openOrdersAdminAccount solanago.PublicKey,
	userTokenAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
	marketVaultAccount solanago.PublicKey,
	oracleAAccount solanago.PublicKey,
	oracleBAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_EditOrderPegged[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `clientOrderIdParam`:
		err = enc__.Encode(clientOrderIdParam)
		if err != nil {
			return nil, errors.NewField("clientOrderIdParam", err)
		}
		// Serialize `expectedCancelSizeParam`:
		err = enc__.Encode(expectedCancelSizeParam)
		if err != nil {
			return nil, errors.NewField("expectedCancelSizeParam", err)
		}
		// Serialize `placeOrderParam`:
		err = enc__.Encode(placeOrderParam)
		if err != nil {
			return nil, errors.NewField("placeOrderParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "open_orders_admin": Read-only, Signer, Optional
		accounts__.Append(solanago.NewAccountMeta(openOrdersAdminAccount, false, true))
		// Account 3 "user_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAccount, true, false))
		// Account 4 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 5 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 6 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
		// Account 7 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
		// Account 8 "market_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketVaultAccount, true, false))
		// Account 9 "oracle_a": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleAAccount, false, false))
		// Account 10 "oracle_b": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleBAccount, false, false))
		// Account 11 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "place_orders" instruction.
// Place multiple orders
func NewPlaceOrdersInstruction(
	// Params:
	ordersTypeParam PlaceOrderType,
	bidsParam []PlaceMultipleOrdersArgs,
	asksParam []PlaceMultipleOrdersArgs,
	limitParam uint8,

	// Accounts:
	signerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	openOrdersAdminAccount solanago.PublicKey,
	userQuoteAccountAccount solanago.PublicKey,
	userBaseAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
	marketQuoteVaultAccount solanago.PublicKey,
	marketBaseVaultAccount solanago.PublicKey,
	oracleAAccount solanago.PublicKey,
	oracleBAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_PlaceOrders[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `ordersTypeParam`:
		err = enc__.Encode(ordersTypeParam)
		if err != nil {
			return nil, errors.NewField("ordersTypeParam", err)
		}
		// Serialize `bidsParam`:
		err = enc__.Encode(bidsParam)
		if err != nil {
			return nil, errors.NewField("bidsParam", err)
		}
		// Serialize `asksParam`:
		err = enc__.Encode(asksParam)
		if err != nil {
			return nil, errors.NewField("asksParam", err)
		}
		// Serialize `limitParam`:
		err = enc__.Encode(limitParam)
		if err != nil {
			return nil, errors.NewField("limitParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "open_orders_admin": Read-only, Signer, Optional
		accounts__.Append(solanago.NewAccountMeta(openOrdersAdminAccount, false, true))
		// Account 3 "user_quote_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteAccountAccount, true, false))
		// Account 4 "user_base_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseAccountAccount, true, false))
		// Account 5 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 6 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 7 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
		// Account 8 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
		// Account 9 "market_quote_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketQuoteVaultAccount, true, false))
		// Account 10 "market_base_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketBaseVaultAccount, true, false))
		// Account 11 "oracle_a": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleAAccount, false, false))
		// Account 12 "oracle_b": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleBAccount, false, false))
		// Account 13 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "cancel_all_and_place_orders" instruction.
// Cancel orders and place multiple orders.
func NewCancelAllAndPlaceOrdersInstruction(
	// Params:
	ordersTypeParam PlaceOrderType,
	bidsParam []PlaceMultipleOrdersArgs,
	asksParam []PlaceMultipleOrdersArgs,
	limitParam uint8,

	// Accounts:
	signerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	openOrdersAdminAccount solanago.PublicKey,
	userQuoteAccountAccount solanago.PublicKey,
	userBaseAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
	marketQuoteVaultAccount solanago.PublicKey,
	marketBaseVaultAccount solanago.PublicKey,
	oracleAAccount solanago.PublicKey,
	oracleBAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CancelAllAndPlaceOrders[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `ordersTypeParam`:
		err = enc__.Encode(ordersTypeParam)
		if err != nil {
			return nil, errors.NewField("ordersTypeParam", err)
		}
		// Serialize `bidsParam`:
		err = enc__.Encode(bidsParam)
		if err != nil {
			return nil, errors.NewField("bidsParam", err)
		}
		// Serialize `asksParam`:
		err = enc__.Encode(asksParam)
		if err != nil {
			return nil, errors.NewField("asksParam", err)
		}
		// Serialize `limitParam`:
		err = enc__.Encode(limitParam)
		if err != nil {
			return nil, errors.NewField("limitParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "open_orders_admin": Read-only, Signer, Optional
		accounts__.Append(solanago.NewAccountMeta(openOrdersAdminAccount, false, true))
		// Account 3 "user_quote_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteAccountAccount, true, false))
		// Account 4 "user_base_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseAccountAccount, true, false))
		// Account 5 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 6 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 7 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
		// Account 8 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
		// Account 9 "market_quote_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketQuoteVaultAccount, true, false))
		// Account 10 "market_base_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketBaseVaultAccount, true, false))
		// Account 11 "oracle_a": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleAAccount, false, false))
		// Account 12 "oracle_b": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleBAccount, false, false))
		// Account 13 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "place_order_pegged" instruction.
// Place an oracle-peg order.
func NewPlaceOrderPeggedInstruction(
	// Params:
	argsParam PlaceOrderPeggedArgs,

	// Accounts:
	signerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	openOrdersAdminAccount solanago.PublicKey,
	userTokenAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
	marketVaultAccount solanago.PublicKey,
	oracleAAccount solanago.PublicKey,
	oracleBAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_PlaceOrderPegged[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "open_orders_admin": Read-only, Signer, Optional
		accounts__.Append(solanago.NewAccountMeta(openOrdersAdminAccount, false, true))
		// Account 3 "user_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAccount, true, false))
		// Account 4 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 5 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 6 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
		// Account 7 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
		// Account 8 "market_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketVaultAccount, true, false))
		// Account 9 "oracle_a": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleAAccount, false, false))
		// Account 10 "oracle_b": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleBAccount, false, false))
		// Account 11 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "place_take_order" instruction.
// Place an order that shall take existing liquidity off of the book, not // add a new order off the book. //  // This type of order allows for instant token settlement for the taker.
func NewPlaceTakeOrderInstruction(
	// Params:
	argsParam PlaceTakeOrderArgs,

	// Accounts:
	signerAccount solanago.PublicKey,
	penaltyPayerAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	marketAuthorityAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
	marketBaseVaultAccount solanago.PublicKey,
	marketQuoteVaultAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
	userBaseAccountAccount solanago.PublicKey,
	userQuoteAccountAccount solanago.PublicKey,
	oracleAAccount solanago.PublicKey,
	oracleBAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	openOrdersAdminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_PlaceTakeOrder[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, true, true))
		// Account 1 "penalty_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(penaltyPayerAccount, true, true))
		// Account 2 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 3 "market_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAuthorityAccount, false, false))
		// Account 4 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 5 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
		// Account 6 "market_base_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketBaseVaultAccount, true, false))
		// Account 7 "market_quote_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketQuoteVaultAccount, true, false))
		// Account 8 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
		// Account 9 "user_base_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseAccountAccount, true, false))
		// Account 10 "user_quote_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteAccountAccount, true, false))
		// Account 11 "oracle_a": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleAAccount, false, false))
		// Account 12 "oracle_b": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(oracleBAccount, false, false))
		// Account 13 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 14 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 15 "open_orders_admin": Read-only, Signer, Optional
		accounts__.Append(solanago.NewAccountMeta(openOrdersAdminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "consume_events" instruction.
// Process up to `limit` [events](crate::state::AnyEvent). //  // When a user places a 'take' order, they do not know beforehand which // market maker will have placed the 'make' order that they get executed // against. This prevents them from passing in a market maker's // [`OpenOrdersAccount`](crate::state::OpenOrdersAccount), which is needed // to credit/debit the relevant tokens to/from the maker. As such, Openbook // uses a 'crank' system, where `place_order` only emits events, and // `consume_events` handles token settlement. //  // Currently, there are two types of events: [`FillEvent`](crate::state::FillEvent)s // and [`OutEvent`](crate::state::OutEvent)s. //  // A `FillEvent` is emitted when an order is filled, and it is handled by // debiting whatever the taker is selling from the taker and crediting // it to the maker, and debiting whatever the taker is buying from the // maker and crediting it to the taker. Note that *no tokens are moved*, // these are just debits and credits to each party's [`Position`](crate::state::Position). //  // An `OutEvent` is emitted when a limit order needs to be removed from // the book during a `place_order` invocation, and it is handled by // crediting whatever the maker would have sold (quote token in a bid, // base token in an ask) back to the maker.
func NewConsumeEventsInstruction(
	// Params:
	limitParam uint64,

	// Accounts:
	consumeEventsAdminAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ConsumeEvents[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `limitParam`:
		err = enc__.Encode(limitParam)
		if err != nil {
			return nil, errors.NewField("limitParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "consume_events_admin": Read-only, Signer, Optional
		accounts__.Append(solanago.NewAccountMeta(consumeEventsAdminAccount, false, true))
		// Account 1 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 2 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "consume_given_events" instruction.
// Process the [events](crate::state::AnyEvent) at the given positions.
func NewConsumeGivenEventsInstruction(
	// Params:
	slotsParam []uint64,

	// Accounts:
	consumeEventsAdminAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	eventHeapAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ConsumeGivenEvents[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `slotsParam`:
		err = enc__.Encode(slotsParam)
		if err != nil {
			return nil, errors.NewField("slotsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "consume_events_admin": Read-only, Signer, Optional
		accounts__.Append(solanago.NewAccountMeta(consumeEventsAdminAccount, false, true))
		// Account 1 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 2 "event_heap": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventHeapAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "cancel_order" instruction.
// Cancel an order by its `order_id`. //  // Note that this doesn't emit an [`OutEvent`](crate::state::OutEvent) because a // maker knows that they will be passing in their own [`OpenOrdersAccount`](crate::state::OpenOrdersAccount).
func NewCancelOrderInstruction(
	// Params:
	orderIdParam binary.Uint128,

	// Accounts:
	signerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CancelOrder[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `orderIdParam`:
		err = enc__.Encode(orderIdParam)
		if err != nil {
			return nil, errors.NewField("orderIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 3 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 4 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "cancel_order_by_client_order_id" instruction.
// Cancel an order by its `client_order_id`. //  // Note that this doesn't emit an [`OutEvent`](crate::state::OutEvent) because a // maker knows that they will be passing in their own [`OpenOrdersAccount`](crate::state::OpenOrdersAccount).
func NewCancelOrderByClientOrderIdInstruction(
	// Params:
	clientOrderIdParam uint64,

	// Accounts:
	signerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CancelOrderByClientOrderId[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `clientOrderIdParam`:
		err = enc__.Encode(clientOrderIdParam)
		if err != nil {
			return nil, errors.NewField("clientOrderIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 3 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 4 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "cancel_all_orders" instruction.
// Cancel up to `limit` orders, optionally filtering by side
func NewCancelAllOrdersInstruction(
	// Params:
	sideOptionParam *Side,
	limitParam uint8,

	// Accounts:
	signerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CancelAllOrders[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `sideOptionParam` (optional):
		{
			if sideOptionParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("sideOptionParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("sideOptionParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(sideOptionParam)
				if err != nil {
					return nil, errors.NewField("sideOptionParam", err)
				}
			}
		}
		// Serialize `limitParam`:
		err = enc__.Encode(limitParam)
		if err != nil {
			return nil, errors.NewField("limitParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 3 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 4 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "deposit" instruction.
// Deposit a certain amount of `base` and `quote` lamports into one's // [`Position`](crate::state::Position). //  // Makers might wish to `deposit`, rather than have actual tokens moved for // each trade, in order to reduce CUs.
func NewDepositInstruction(
	// Params:
	baseAmountParam uint64,
	quoteAmountParam uint64,

	// Accounts:
	ownerAccount solanago.PublicKey,
	userBaseAccountAccount solanago.PublicKey,
	userQuoteAccountAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	marketBaseVaultAccount solanago.PublicKey,
	marketQuoteVaultAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Deposit[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `baseAmountParam`:
		err = enc__.Encode(baseAmountParam)
		if err != nil {
			return nil, errors.NewField("baseAmountParam", err)
		}
		// Serialize `quoteAmountParam`:
		err = enc__.Encode(quoteAmountParam)
		if err != nil {
			return nil, errors.NewField("quoteAmountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, true))
		// Account 1 "user_base_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseAccountAccount, true, false))
		// Account 2 "user_quote_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteAccountAccount, true, false))
		// Account 3 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 4 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 5 "market_base_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketBaseVaultAccount, true, false))
		// Account 6 "market_quote_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketQuoteVaultAccount, true, false))
		// Account 7 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "refill" instruction.
// Refill a certain amount of `base` and `quote` lamports. The amount being passed is the // total lamports that the [`Position`](crate::state::Position) will have. //  // Makers might wish to `refill`, rather than have actual tokens moved for // each trade, in order to reduce CUs.
func NewRefillInstruction(
	// Params:
	baseAmountParam uint64,
	quoteAmountParam uint64,

	// Accounts:
	ownerAccount solanago.PublicKey,
	userBaseAccountAccount solanago.PublicKey,
	userQuoteAccountAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	marketBaseVaultAccount solanago.PublicKey,
	marketQuoteVaultAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Refill[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `baseAmountParam`:
		err = enc__.Encode(baseAmountParam)
		if err != nil {
			return nil, errors.NewField("baseAmountParam", err)
		}
		// Serialize `quoteAmountParam`:
		err = enc__.Encode(quoteAmountParam)
		if err != nil {
			return nil, errors.NewField("quoteAmountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, true))
		// Account 1 "user_base_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseAccountAccount, true, false))
		// Account 2 "user_quote_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteAccountAccount, true, false))
		// Account 3 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 4 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 5 "market_base_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketBaseVaultAccount, true, false))
		// Account 6 "market_quote_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketQuoteVaultAccount, true, false))
		// Account 7 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "settle_funds" instruction.
// Withdraw any available tokens.
func NewSettleFundsInstruction(
	ownerAccount solanago.PublicKey,
	penaltyPayerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	marketAuthorityAccount solanago.PublicKey,
	marketBaseVaultAccount solanago.PublicKey,
	marketQuoteVaultAccount solanago.PublicKey,
	userBaseAccountAccount solanago.PublicKey,
	userQuoteAccountAccount solanago.PublicKey,
	referrerAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "owner": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, true, true))
		// Account 1 "penalty_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(penaltyPayerAccount, true, true))
		// Account 2 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 3 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 4 "market_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAuthorityAccount, false, false))
		// Account 5 "market_base_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketBaseVaultAccount, true, false))
		// Account 6 "market_quote_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketQuoteVaultAccount, true, false))
		// Account 7 "user_base_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseAccountAccount, true, false))
		// Account 8 "user_quote_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteAccountAccount, true, false))
		// Account 9 "referrer_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(referrerAccountAccount, true, false))
		// Account 10 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 11 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "settle_funds_expired" instruction.
// Withdraw any available tokens when the market is expired (only // [`close_market_admin`](crate::state::Market::close_market_admin)).
func NewSettleFundsExpiredInstruction(
	closeMarketAdminAccount solanago.PublicKey,
	ownerAccount solanago.PublicKey,
	penaltyPayerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	marketAuthorityAccount solanago.PublicKey,
	marketBaseVaultAccount solanago.PublicKey,
	marketQuoteVaultAccount solanago.PublicKey,
	userBaseAccountAccount solanago.PublicKey,
	userQuoteAccountAccount solanago.PublicKey,
	referrerAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "close_market_admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(closeMarketAdminAccount, false, true))
		// Account 1 "owner": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, true, true))
		// Account 2 "penalty_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(penaltyPayerAccount, true, true))
		// Account 3 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 4 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 5 "market_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAuthorityAccount, false, false))
		// Account 6 "market_base_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketBaseVaultAccount, true, false))
		// Account 7 "market_quote_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketQuoteVaultAccount, true, false))
		// Account 8 "user_base_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseAccountAccount, true, false))
		// Account 9 "user_quote_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteAccountAccount, true, false))
		// Account 10 "referrer_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(referrerAccountAccount, true, false))
		// Account 11 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 12 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "sweep_fees" instruction.
// Sweep fees, as a [`Market`](crate::state::Market)'s admin.
func NewSweepFeesInstruction(
	collectFeeAdminAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	marketAuthorityAccount solanago.PublicKey,
	marketQuoteVaultAccount solanago.PublicKey,
	tokenReceiverAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "collect_fee_admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(collectFeeAdminAccount, false, true))
		// Account 1 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 2 "market_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAuthorityAccount, false, false))
		// Account 3 "market_quote_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketQuoteVaultAccount, true, false))
		// Account 4 "token_receiver_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenReceiverAccountAccount, true, false))
		// Account 5 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "set_delegate" instruction.
// Update the [`delegate`](crate::state::OpenOrdersAccount::delegate) of an open orders account.
func NewSetDelegateInstruction(
	ownerAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	delegateAccountAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "owner": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, true, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "delegate_account": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(delegateAccountAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "set_market_expired" instruction.
// Set market to expired before pruning orders and closing the market (only // [`close_market_admin`](crate::state::Market::close_market_admin)).
func NewSetMarketExpiredInstruction(
	closeMarketAdminAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "close_market_admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(closeMarketAdminAccount, false, true))
		// Account 1 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "prune_orders" instruction.
// Remove orders from the book when the market is expired (only // [`close_market_admin`](crate::state::Market::close_market_admin)).
func NewPruneOrdersInstruction(
	// Params:
	limitParam uint8,

	// Accounts:
	closeMarketAdminAccount solanago.PublicKey,
	openOrdersAccountAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	bidsAccount solanago.PublicKey,
	asksAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_PruneOrders[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `limitParam`:
		err = enc__.Encode(limitParam)
		if err != nil {
			return nil, errors.NewField("limitParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "close_market_admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(closeMarketAdminAccount, false, true))
		// Account 1 "open_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(openOrdersAccountAccount, true, false))
		// Account 2 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 3 "bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bidsAccount, true, false))
		// Account 4 "asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(asksAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "stub_oracle_create" instruction.
func NewStubOracleCreateInstruction(
	// Params:
	priceParam float64,

	// Accounts:
	payerAccount solanago.PublicKey,
	ownerAccount solanago.PublicKey,
	oracleAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_StubOracleCreate[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `priceParam`:
		err = enc__.Encode(priceParam)
		if err != nil {
			return nil, errors.NewField("priceParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, true))
		// Account 2 "oracle": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(oracleAccount, true, false))
		// Account 3 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 4 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "stub_oracle_close" instruction.
func NewStubOracleCloseInstruction(
	ownerAccount solanago.PublicKey,
	oracleAccount solanago.PublicKey,
	solDestinationAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, true))
		// Account 1 "oracle": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(oracleAccount, true, false))
		// Account 2 "sol_destination": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(solDestinationAccount, true, false))
		// Account 3 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "stub_oracle_set" instruction.
func NewStubOracleSetInstruction(
	// Params:
	priceParam float64,

	// Accounts:
	ownerAccount solanago.PublicKey,
	oracleAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_StubOracleSet[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `priceParam`:
		err = enc__.Encode(priceParam)
		if err != nil {
			return nil, errors.NewField("priceParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, true))
		// Account 1 "oracle": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(oracleAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
