// Code generated by MockGen. DO NOT EDIT.
// Source: encryptor.go
//
// Generated by this command:
//
//	mockgen -source=encryptor.go -destination=mocks/encryptor_mock.go -package=cryptoMocks
//

// Package cryptoMocks is a generated GoMock package.
package cryptoMocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEncryptorInterface is a mock of EncryptorInterface interface.
type MockEncryptorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptorInterfaceMockRecorder
	isgomock struct{}
}

// MockEncryptorInterfaceMockRecorder is the mock recorder for MockEncryptorInterface.
type MockEncryptorInterfaceMockRecorder struct {
	mock *MockEncryptorInterface
}

// NewMockEncryptorInterface creates a new mock instance.
func NewMockEncryptorInterface(ctrl *gomock.Controller) *MockEncryptorInterface {
	mock := &MockEncryptorInterface{ctrl: ctrl}
	mock.recorder = &MockEncryptorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptorInterface) EXPECT() *MockEncryptorInterfaceMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptorInterface) Decrypt(encodedCiphertext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", encodedCiphertext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptorInterfaceMockRecorder) Decrypt(encodedCiphertext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptorInterface)(nil).Decrypt), encodedCiphertext)
}

// Encrypt mocks base method.
func (m *MockEncryptorInterface) Encrypt(plaintext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plaintext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptorInterfaceMockRecorder) Encrypt(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptorInterface)(nil).Encrypt), plaintext)
}
