// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package raydium_amm

import (
	"fmt"

	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_TargetOrders:
		value := new(TargetOrders)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as TargetOrders: %w", err)
		}
		return value, nil
	case Account_Fees:
		value := new(Fees)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Fees: %w", err)
		}
		return value, nil
	case Account_AmmInfo:
		value := new(AmmInfo)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as AmmInfo: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_TargetOrders(accountData []byte) (*TargetOrders, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_TargetOrders {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_TargetOrders, binary.FormatDiscriminator(discriminator))
	}
	acc := new(TargetOrders)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type TargetOrders: %w", err)
	}
	return acc, nil
}

func ParseAccount_Fees(accountData []byte) (*Fees, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Fees {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Fees, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Fees)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Fees: %w", err)
	}
	return acc, nil
}

func ParseAccount_AmmInfo(accountData []byte) (*AmmInfo, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_AmmInfo {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_AmmInfo, binary.FormatDiscriminator(discriminator))
	}
	acc := new(AmmInfo)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type AmmInfo: %w", err)
	}
	return acc, nil
}
