// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains errors.

package raydium_amm

import (
	"encoding/json"
	"errors"
	"fmt"

	ag_jsonrpc "github.com/gagliardetto/solana-go/rpc/jsonrpc"
)

var (
	_ *json.Encoder        = nil
	_ *ag_jsonrpc.RPCError = nil
	_ fmt.Formatter        = nil
	_                      = errors.ErrUnsupported
)
var (
	ErrAlreadyInUse = &customErrorDef{
		code: 0,
		msg:  "AlreadyInUse",
		name: "AlreadyInUse",
	}
	ErrInvalidProgramAddress = &customErrorDef{
		code: 1,
		msg:  "InvalidProgramAddress",
		name: "InvalidProgramAddress",
	}
	ErrExpectedMint = &customErrorDef{
		code: 2,
		msg:  "ExpectedMint",
		name: "ExpectedMint",
	}
	ErrExpectedAccount = &customErrorDef{
		code: 3,
		msg:  "ExpectedAccount",
		name: "ExpectedAccount",
	}
	ErrInvalidCoinVault = &customErrorDef{
		code: 4,
		msg:  "InvalidCoinVault",
		name: "InvalidCoinVault",
	}
	ErrInvalidPCVault = &customErrorDef{
		code: 5,
		msg:  "InvalidPCVault",
		name: "InvalidPCVault",
	}
	ErrInvalidTokenLP = &customErrorDef{
		code: 6,
		msg:  "InvalidTokenLP",
		name: "InvalidTokenLP",
	}
	ErrInvalidDestTokenCoin = &customErrorDef{
		code: 7,
		msg:  "InvalidDestTokenCoin",
		name: "InvalidDestTokenCoin",
	}
	ErrInvalidDestTokenPC = &customErrorDef{
		code: 8,
		msg:  "InvalidDestTokenPC",
		name: "InvalidDestTokenPC",
	}
	ErrInvalidPoolMint = &customErrorDef{
		code: 9,
		msg:  "InvalidPoolMint",
		name: "InvalidPoolMint",
	}
	ErrInvalidOpenOrders = &customErrorDef{
		code: 10,
		msg:  "InvalidOpenOrders",
		name: "InvalidOpenOrders",
	}
	ErrInvalidSerumMarket = &customErrorDef{
		code: 11,
		msg:  "InvalidSerumMarket",
		name: "InvalidSerumMarket",
	}
	ErrInvalidSerumProgram = &customErrorDef{
		code: 12,
		msg:  "InvalidSerumProgram",
		name: "InvalidSerumProgram",
	}
	ErrInvalidTargetOrders = &customErrorDef{
		code: 13,
		msg:  "InvalidTargetOrders",
		name: "InvalidTargetOrders",
	}
	ErrInvalidWithdrawQueue = &customErrorDef{
		code: 14,
		msg:  "InvalidWithdrawQueue",
		name: "InvalidWithdrawQueue",
	}
	ErrInvalidTempLp = &customErrorDef{
		code: 15,
		msg:  "InvalidTempLp",
		name: "InvalidTempLp",
	}
	ErrInvalidCoinMint = &customErrorDef{
		code: 16,
		msg:  "InvalidCoinMint",
		name: "InvalidCoinMint",
	}
	ErrInvalidPCMint = &customErrorDef{
		code: 17,
		msg:  "InvalidPCMint",
		name: "InvalidPCMint",
	}
	ErrInvalidOwner = &customErrorDef{
		code: 18,
		msg:  "InvalidOwner",
		name: "InvalidOwner",
	}
	ErrInvalidSupply = &customErrorDef{
		code: 19,
		msg:  "InvalidSupply",
		name: "InvalidSupply",
	}
	ErrInvalidDelegate = &customErrorDef{
		code: 20,
		msg:  "InvalidDelegate",
		name: "InvalidDelegate",
	}
	ErrInvalidSignAccount = &customErrorDef{
		code: 21,
		msg:  "Invalid Sign Account",
		name: "InvalidSignAccount",
	}
	ErrInvalidStatus = &customErrorDef{
		code: 22,
		msg:  "InvalidStatus",
		name: "InvalidStatus",
	}
	ErrInvalidInstruction = &customErrorDef{
		code: 23,
		msg:  "Invalid instruction",
		name: "InvalidInstruction",
	}
	ErrWrongAccountsNumber = &customErrorDef{
		code: 24,
		msg:  "Wrong accounts number",
		name: "WrongAccountsNumber",
	}
	ErrWithdrawTransferBusy = &customErrorDef{
		code: 25,
		msg:  "Withdraw_transfer is busy",
		name: "WithdrawTransferBusy",
	}
	ErrWithdrawQueueFull = &customErrorDef{
		code: 26,
		msg:  "WithdrawQueue is full",
		name: "WithdrawQueueFull",
	}
	ErrWithdrawQueueEmpty = &customErrorDef{
		code: 27,
		msg:  "WithdrawQueue is empty",
		name: "WithdrawQueueEmpty",
	}
	ErrInvalidParamsSet = &customErrorDef{
		code: 28,
		msg:  "Params Set is invalid",
		name: "InvalidParamsSet",
	}
	ErrInvalidInput = &customErrorDef{
		code: 29,
		msg:  "InvalidInput",
		name: "InvalidInput",
	}
	ErrExceededSlippage = &customErrorDef{
		code: 30,
		msg:  "instruction exceeds desired slippage limit",
		name: "ExceededSlippage",
	}
	ErrCalculationExRateFailure = &customErrorDef{
		code: 31,
		msg:  "CalculationExRateFailure",
		name: "CalculationExRateFailure",
	}
	ErrCheckedSubOverflow = &customErrorDef{
		code: 32,
		msg:  "Checked_Sub Overflow",
		name: "CheckedSubOverflow",
	}
	ErrCheckedAddOverflow = &customErrorDef{
		code: 33,
		msg:  "Checked_Add Overflow",
		name: "CheckedAddOverflow",
	}
	ErrCheckedMulOverflow = &customErrorDef{
		code: 34,
		msg:  "Checked_Mul Overflow",
		name: "CheckedMulOverflow",
	}
	ErrCheckedDivOverflow = &customErrorDef{
		code: 35,
		msg:  "Checked_Div Overflow",
		name: "CheckedDivOverflow",
	}
	ErrCheckedEmptyFunds = &customErrorDef{
		code: 36,
		msg:  "Empty Funds",
		name: "CheckedEmptyFunds",
	}
	ErrCalcPnlError = &customErrorDef{
		code: 37,
		msg:  "Calc pnl error",
		name: "CalcPnlError",
	}
	ErrInvalidSplTokenProgram = &customErrorDef{
		code: 38,
		msg:  "InvalidSplTokenProgram",
		name: "InvalidSplTokenProgram",
	}
	ErrTakePnlError = &customErrorDef{
		code: 39,
		msg:  "Take Pnl error",
		name: "TakePnlError",
	}
	ErrInsufficientFunds = &customErrorDef{
		code: 40,
		msg:  "Insufficient funds",
		name: "InsufficientFunds",
	}
	ErrConversionFailure = &customErrorDef{
		code: 41,
		msg:  "Conversion to u64 failed with an overflow or underflow",
		name: "ConversionFailure",
	}
	ErrInvalidUserToken = &customErrorDef{
		code: 42,
		msg:  "user token input does not match amm",
		name: "InvalidUserToken",
	}
	ErrInvalidSrmMint = &customErrorDef{
		code: 43,
		msg:  "InvalidSrmMint",
		name: "InvalidSrmMint",
	}
	ErrInvalidSrmToken = &customErrorDef{
		code: 44,
		msg:  "InvalidSrmToken",
		name: "InvalidSrmToken",
	}
	ErrTooManyOpenOrders = &customErrorDef{
		code: 45,
		msg:  "TooManyOpenOrders",
		name: "TooManyOpenOrders",
	}
	ErrOrderAtSlotIsPlaced = &customErrorDef{
		code: 46,
		msg:  "OrderAtSlotIsPlaced",
		name: "OrderAtSlotIsPlaced",
	}
	ErrInvalidSysProgramAddress = &customErrorDef{
		code: 47,
		msg:  "InvalidSysProgramAddress",
		name: "InvalidSysProgramAddress",
	}
	ErrInvalidFee = &customErrorDef{
		code: 48,
		msg:  "The provided fee does not match the program owner's constraints",
		name: "InvalidFee",
	}
	ErrRepeatCreateAmm = &customErrorDef{
		code: 49,
		msg:  "Repeat create amm about market",
		name: "RepeatCreateAmm",
	}
	ErrNotAllowZeroLP = &customErrorDef{
		code: 50,
		msg:  "Not allow Zero LP",
		name: "NotAllowZeroLP",
	}
	ErrInvalidCloseAuthority = &customErrorDef{
		code: 51,
		msg:  "Token account has a close authority",
		name: "InvalidCloseAuthority",
	}
	ErrInvalidFreezeAuthority = &customErrorDef{
		code: 52,
		msg:  "Pool token mint has a freeze authority",
		name: "InvalidFreezeAuthority",
	}
	ErrInvalidReferPCMint = &customErrorDef{
		code: 53,
		msg:  "InvalidReferPCMint",
		name: "InvalidReferPCMint",
	}
	ErrInvalidConfigAccount = &customErrorDef{
		code: 54,
		msg:  "InvalidConfigAccount",
		name: "InvalidConfigAccount",
	}
	ErrRepeatCreateConfigAccount = &customErrorDef{
		code: 55,
		msg:  "Repeat create staking config account",
		name: "RepeatCreateConfigAccount",
	}
	ErrUnknownAmmError = &customErrorDef{
		code: 56,
		msg:  "Unknown Amm Error",
		name: "UnknownAmmError",
	}
	Errors = map[int]CustomError{
		0:  ErrAlreadyInUse,
		1:  ErrInvalidProgramAddress,
		10: ErrInvalidOpenOrders,
		11: ErrInvalidSerumMarket,
		12: ErrInvalidSerumProgram,
		13: ErrInvalidTargetOrders,
		14: ErrInvalidWithdrawQueue,
		15: ErrInvalidTempLp,
		16: ErrInvalidCoinMint,
		17: ErrInvalidPCMint,
		18: ErrInvalidOwner,
		19: ErrInvalidSupply,
		2:  ErrExpectedMint,
		20: ErrInvalidDelegate,
		21: ErrInvalidSignAccount,
		22: ErrInvalidStatus,
		23: ErrInvalidInstruction,
		24: ErrWrongAccountsNumber,
		25: ErrWithdrawTransferBusy,
		26: ErrWithdrawQueueFull,
		27: ErrWithdrawQueueEmpty,
		28: ErrInvalidParamsSet,
		29: ErrInvalidInput,
		3:  ErrExpectedAccount,
		30: ErrExceededSlippage,
		31: ErrCalculationExRateFailure,
		32: ErrCheckedSubOverflow,
		33: ErrCheckedAddOverflow,
		34: ErrCheckedMulOverflow,
		35: ErrCheckedDivOverflow,
		36: ErrCheckedEmptyFunds,
		37: ErrCalcPnlError,
		38: ErrInvalidSplTokenProgram,
		39: ErrTakePnlError,
		4:  ErrInvalidCoinVault,
		40: ErrInsufficientFunds,
		41: ErrConversionFailure,
		42: ErrInvalidUserToken,
		43: ErrInvalidSrmMint,
		44: ErrInvalidSrmToken,
		45: ErrTooManyOpenOrders,
		46: ErrOrderAtSlotIsPlaced,
		47: ErrInvalidSysProgramAddress,
		48: ErrInvalidFee,
		49: ErrRepeatCreateAmm,
		5:  ErrInvalidPCVault,
		50: ErrNotAllowZeroLP,
		51: ErrInvalidCloseAuthority,
		52: ErrInvalidFreezeAuthority,
		53: ErrInvalidReferPCMint,
		54: ErrInvalidConfigAccount,
		55: ErrRepeatCreateConfigAccount,
		56: ErrUnknownAmmError,
		6:  ErrInvalidTokenLP,
		7:  ErrInvalidDestTokenCoin,
		8:  ErrInvalidDestTokenPC,
		9:  ErrInvalidPoolMint,
	}
)

type CustomError interface {
	Code() int
	Name() string
	Error() string
}

type customErrorDef struct {
	code int
	name string
	msg  string
}

func (e *customErrorDef) Code() int {
	return e.code
}

func (e *customErrorDef) Name() string {
	return e.name
}

func (e *customErrorDef) Error() string {
	return fmt.Sprintf("%s(%d): %s", e.name, e.code, e.msg)
}

func DecodeCustomError(rpcErr error) (err error, ok bool) {
	if errCode, o := decodeErrorCode(rpcErr); o {
		if customErr, o := Errors[errCode]; o {
			err = customErr
			ok = true
			return
		}
	}
	return
}

func decodeErrorCode(rpcErr error) (errorCode int, ok bool) {
	var jErr *ag_jsonrpc.RPCError
	if errors.As(rpcErr, &jErr) && jErr.Data != nil {
		if root, o := jErr.Data.(map[string]interface{}); o {
			if rootErr, o := root["err"].(map[string]interface{}); o {
				if rootErrInstructionError, o := rootErr["InstructionError"]; o {
					if rootErrInstructionErrorItems, o := rootErrInstructionError.([]interface{}); o {
						if len(rootErrInstructionErrorItems) == 2 {
							if v, o := rootErrInstructionErrorItems[1].(map[string]interface{}); o {
								if v2, o := v["Custom"].(json.Number); o {
									if code, err := v2.Int64(); err == nil {
										ok = true
										errorCode = int(code)
									}
								} else if v2, o := v["Custom"].(float64); o {
									ok = true
									errorCode = int(v2)
								}
							}
						}
					}
				}
			}
		}
	}
	return
}
