// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package raydium_amm

import (
	"bytes"
	"fmt"

	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "initialize" instruction.
func NewInitializeInstruction(
	// Params:
	nonceParam uint8,
	openTimeParam uint64,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	lpMintAddressAccount solanago.PublicKey,
	coinMintAddressAccount solanago.PublicKey,
	pcMintAddressAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	poolWithdrawQueueAccount solanago.PublicKey,
	poolTargetOrdersAccountAccount solanago.PublicKey,
	userLpTokenAccountAccount solanago.PublicKey,
	poolTempLpTokenAccountAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	userWalletAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Initialize[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `nonceParam`:
		err = enc__.Encode(nonceParam)
		if err != nil {
			return nil, errors.NewField("nonceParam", err)
		}
		// Serialize `openTimeParam`:
		err = enc__.Encode(openTimeParam)
		if err != nil {
			return nil, errors.NewField("openTimeParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 2 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
		// Account 3 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 4 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 5 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 6 "lp_mint_address": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAddressAccount, true, false))
		// Account 7 "coin_mint_address": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinMintAddressAccount, false, false))
		// Account 8 "pc_mint_address": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(pcMintAddressAccount, false, false))
		// Account 9 "pool_coin_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, false, false))
		// Account 10 "pool_pc_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, false, false))
		// Account 11 "pool_withdraw_queue": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolWithdrawQueueAccount, true, false))
		// Account 12 "pool_target_orders_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolTargetOrdersAccountAccount, true, false))
		// Account 13 "user_lp_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userLpTokenAccountAccount, true, false))
		// Account 14 "pool_temp_lp_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolTempLpTokenAccountAccount, false, false))
		// Account 15 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 16 "serum_market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, false, false))
		// Account 17 "user_wallet": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userWalletAccount, true, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "initialize2" instruction.
func NewInitialize2Instruction(
	// Params:
	nonceParam uint8,
	openTimeParam uint64,
	initPcAmountParam uint64,
	initCoinAmountParam uint64,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	splAssociatedTokenAccountAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	lpMintAccount solanago.PublicKey,
	coinMintAccount solanago.PublicKey,
	pcMintAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	poolWithdrawQueueAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	poolTempLpAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	userWalletAccount solanago.PublicKey,
	userTokenCoinAccount solanago.PublicKey,
	userTokenPcAccount solanago.PublicKey,
	userLpTokenAccountAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Initialize2[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `nonceParam`:
		err = enc__.Encode(nonceParam)
		if err != nil {
			return nil, errors.NewField("nonceParam", err)
		}
		// Serialize `openTimeParam`:
		err = enc__.Encode(openTimeParam)
		if err != nil {
			return nil, errors.NewField("openTimeParam", err)
		}
		// Serialize `initPcAmountParam`:
		err = enc__.Encode(initPcAmountParam)
		if err != nil {
			return nil, errors.NewField("initPcAmountParam", err)
		}
		// Serialize `initCoinAmountParam`:
		err = enc__.Encode(initCoinAmountParam)
		if err != nil {
			return nil, errors.NewField("initCoinAmountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "spl_associated_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(splAssociatedTokenAccountAccount, false, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
		// Account 4 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 5 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 6 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 7 "lp_mint": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAccount, true, false))
		// Account 8 "coin_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinMintAccount, false, false))
		// Account 9 "pc_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(pcMintAccount, false, false))
		// Account 10 "pool_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, true, false))
		// Account 11 "pool_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, true, false))
		// Account 12 "pool_withdraw_queue": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolWithdrawQueueAccount, true, false))
		// Account 13 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 14 "pool_temp_lp": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolTempLpAccount, true, false))
		// Account 15 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 16 "serum_market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, false, false))
		// Account 17 "user_wallet": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userWalletAccount, true, true))
		// Account 18 "user_token_coin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenCoinAccount, true, false))
		// Account 19 "user_token_pc": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenPcAccount, true, false))
		// Account 20 "user_lp_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userLpTokenAccountAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "monitor_step" instruction.
func NewMonitorStepInstruction(
	// Params:
	planOrderLimitParam uint16,
	placeOrderLimitParam uint16,
	cancelOrderLimitParam uint16,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	poolWithdrawQueueAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	serumCoinVaultAccountAccount solanago.PublicKey,
	serumPcVaultAccountAccount solanago.PublicKey,
	serumVaultSignerAccount solanago.PublicKey,
	serumReqQAccount solanago.PublicKey,
	serumEventQAccount solanago.PublicKey,
	serumBidsAccount solanago.PublicKey,
	serumAsksAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_MonitorStep[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `planOrderLimitParam`:
		err = enc__.Encode(planOrderLimitParam)
		if err != nil {
			return nil, errors.NewField("planOrderLimitParam", err)
		}
		// Serialize `placeOrderLimitParam`:
		err = enc__.Encode(placeOrderLimitParam)
		if err != nil {
			return nil, errors.NewField("placeOrderLimitParam", err)
		}
		// Serialize `cancelOrderLimitParam`:
		err = enc__.Encode(cancelOrderLimitParam)
		if err != nil {
			return nil, errors.NewField("cancelOrderLimitParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
		// Account 2 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
		// Account 3 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 4 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 5 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 6 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 7 "pool_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, true, false))
		// Account 8 "pool_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, true, false))
		// Account 9 "pool_withdraw_queue": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolWithdrawQueueAccount, true, false))
		// Account 10 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 11 "serum_market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, true, false))
		// Account 12 "serum_coin_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumCoinVaultAccountAccount, true, false))
		// Account 13 "serum_pc_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumPcVaultAccountAccount, true, false))
		// Account 14 "serum_vault_signer": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumVaultSignerAccount, false, false))
		// Account 15 "serum_req_q": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumReqQAccount, true, false))
		// Account 16 "serum_event_q": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQAccount, true, false))
		// Account 17 "serum_bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumBidsAccount, true, false))
		// Account 18 "serum_asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumAsksAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "deposit" instruction.
func NewDepositInstruction(
	// Params:
	maxCoinAmountParam uint64,
	maxPcAmountParam uint64,
	baseSideParam uint64,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	lpMintAddressAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	userCoinTokenAccountAccount solanago.PublicKey,
	userPcTokenAccountAccount solanago.PublicKey,
	userLpTokenAccountAccount solanago.PublicKey,
	userOwnerAccount solanago.PublicKey,
	serumEventQueueAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Deposit[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `maxCoinAmountParam`:
		err = enc__.Encode(maxCoinAmountParam)
		if err != nil {
			return nil, errors.NewField("maxCoinAmountParam", err)
		}
		// Serialize `maxPcAmountParam`:
		err = enc__.Encode(maxPcAmountParam)
		if err != nil {
			return nil, errors.NewField("maxPcAmountParam", err)
		}
		// Serialize `baseSideParam`:
		err = enc__.Encode(baseSideParam)
		if err != nil {
			return nil, errors.NewField("baseSideParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 2 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 3 "amm_open_orders": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, false, false))
		// Account 4 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 5 "lp_mint_address": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAddressAccount, true, false))
		// Account 6 "pool_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, true, false))
		// Account 7 "pool_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, true, false))
		// Account 8 "serum_market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, false, false))
		// Account 9 "user_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userCoinTokenAccountAccount, true, false))
		// Account 10 "user_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userPcTokenAccountAccount, true, false))
		// Account 11 "user_lp_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userLpTokenAccountAccount, true, false))
		// Account 12 "user_owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userOwnerAccount, false, true))
		// Account 13 "serum_event_queue": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQueueAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "withdraw" instruction.
func NewWithdrawInstruction(
	// Params:
	amountParam uint64,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	lpMintAddressAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	poolWithdrawQueueAccount solanago.PublicKey,
	poolTempLpTokenAccountAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	serumCoinVaultAccountAccount solanago.PublicKey,
	serumPcVaultAccountAccount solanago.PublicKey,
	serumVaultSignerAccount solanago.PublicKey,
	userLpTokenAccountAccount solanago.PublicKey,
	uerCoinTokenAccountAccount solanago.PublicKey,
	uerPcTokenAccountAccount solanago.PublicKey,
	userOwnerAccount solanago.PublicKey,
	serumEventQAccount solanago.PublicKey,
	serumBidsAccount solanago.PublicKey,
	serumAsksAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Withdraw[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 2 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 3 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 4 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 5 "lp_mint_address": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAddressAccount, true, false))
		// Account 6 "pool_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, true, false))
		// Account 7 "pool_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, true, false))
		// Account 8 "pool_withdraw_queue": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolWithdrawQueueAccount, true, false))
		// Account 9 "pool_temp_lp_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolTempLpTokenAccountAccount, true, false))
		// Account 10 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 11 "serum_market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, true, false))
		// Account 12 "serum_coin_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumCoinVaultAccountAccount, true, false))
		// Account 13 "serum_pc_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumPcVaultAccountAccount, true, false))
		// Account 14 "serum_vault_signer": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumVaultSignerAccount, false, false))
		// Account 15 "user_lp_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userLpTokenAccountAccount, true, false))
		// Account 16 "uer_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(uerCoinTokenAccountAccount, true, false))
		// Account 17 "uer_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(uerPcTokenAccountAccount, true, false))
		// Account 18 "user_owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userOwnerAccount, false, true))
		// Account 19 "serum_event_q": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQAccount, true, false))
		// Account 20 "serum_bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumBidsAccount, true, false))
		// Account 21 "serum_asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumAsksAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "migrate_to_open_book" instruction.
func NewMigrateToOpenBookInstruction(
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	ammTokenCoinAccount solanago.PublicKey,
	ammTokenPcAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	serumBidsAccount solanago.PublicKey,
	serumAsksAccount solanago.PublicKey,
	serumEventQueueAccount solanago.PublicKey,
	serumCoinVaultAccount solanago.PublicKey,
	serumPcVaultAccount solanago.PublicKey,
	serumVaultSignerAccount solanago.PublicKey,
	newAmmOpenOrdersAccount solanago.PublicKey,
	newSerumProgramAccount solanago.PublicKey,
	newSerumMarketAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 2 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
		// Account 3 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 4 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 5 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 6 "amm_token_coin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTokenCoinAccount, true, false))
		// Account 7 "amm_token_pc": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTokenPcAccount, true, false))
		// Account 8 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 9 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 10 "serum_market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, true, false))
		// Account 11 "serum_bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumBidsAccount, true, false))
		// Account 12 "serum_asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumAsksAccount, true, false))
		// Account 13 "serum_event_queue": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQueueAccount, true, false))
		// Account 14 "serum_coin_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumCoinVaultAccount, true, false))
		// Account 15 "serum_pc_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumPcVaultAccount, true, false))
		// Account 16 "serum_vault_signer": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumVaultSignerAccount, false, false))
		// Account 17 "new_amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(newAmmOpenOrdersAccount, true, false))
		// Account 18 "new_serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(newSerumProgramAccount, false, false))
		// Account 19 "new_serum_market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(newSerumMarketAccount, false, false))
		// Account 20 "admin": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, true, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "set_params" instruction.
func NewSetParamsInstruction(
	// Params:
	paramParam uint8,
	valueParam *uint64,
	newPubkeyParam *solanago.PublicKey,
	feesParam *Fees,
	lastOrderDistanceParam *LastOrderDistance,
	needTakeAmountsParam *NeedTake,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	ammCoinVaultAccount solanago.PublicKey,
	ammPcVaultAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	serumCoinVaultAccount solanago.PublicKey,
	serumPcVaultAccount solanago.PublicKey,
	serumVaultSignerAccount solanago.PublicKey,
	serumEventQueueAccount solanago.PublicKey,
	serumBidsAccount solanago.PublicKey,
	serumAsksAccount solanago.PublicKey,
	ammAdminAccountAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetParams[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramParam`:
		err = enc__.Encode(paramParam)
		if err != nil {
			return nil, errors.NewField("paramParam", err)
		}
		// Serialize `valueParam` (optional):
		{
			if valueParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("valueParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("valueParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(valueParam)
				if err != nil {
					return nil, errors.NewField("valueParam", err)
				}
			}
		}
		// Serialize `newPubkeyParam` (optional):
		{
			if newPubkeyParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("newPubkeyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("newPubkeyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(newPubkeyParam)
				if err != nil {
					return nil, errors.NewField("newPubkeyParam", err)
				}
			}
		}
		// Serialize `feesParam` (optional):
		{
			if feesParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("feesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("feesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(feesParam)
				if err != nil {
					return nil, errors.NewField("feesParam", err)
				}
			}
		}
		// Serialize `lastOrderDistanceParam` (optional):
		{
			if lastOrderDistanceParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("lastOrderDistanceParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("lastOrderDistanceParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(lastOrderDistanceParam)
				if err != nil {
					return nil, errors.NewField("lastOrderDistanceParam", err)
				}
			}
		}
		// Serialize `needTakeAmountsParam` (optional):
		{
			if needTakeAmountsParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("needTakeAmountsParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("needTakeAmountsParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(needTakeAmountsParam)
				if err != nil {
					return nil, errors.NewField("needTakeAmountsParam", err)
				}
			}
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 2 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 3 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 4 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 5 "amm_coin_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammCoinVaultAccount, true, false))
		// Account 6 "amm_pc_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammPcVaultAccount, true, false))
		// Account 7 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 8 "serum_market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, true, false))
		// Account 9 "serum_coin_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumCoinVaultAccount, true, false))
		// Account 10 "serum_pc_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumPcVaultAccount, true, false))
		// Account 11 "serum_vault_signer": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumVaultSignerAccount, false, false))
		// Account 12 "serum_event_queue": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQueueAccount, true, false))
		// Account 13 "serum_bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumBidsAccount, true, false))
		// Account 14 "serum_asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumAsksAccount, true, false))
		// Account 15 "amm_admin_account": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAdminAccountAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "withdraw_pnl" instruction.
func NewWithdrawPnlInstruction(
	tokenProgramAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammConfigAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	coinPnlTokenAccountAccount solanago.PublicKey,
	pcPnlTokenAccountAccount solanago.PublicKey,
	pnlOwnerAccountAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	serumEventQueueAccount solanago.PublicKey,
	serumCoinVaultAccountAccount solanago.PublicKey,
	serumPcVaultAccountAccount solanago.PublicKey,
	serumVaultSignerAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 2 "amm_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammConfigAccount, false, false))
		// Account 3 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 4 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 5 "pool_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, true, false))
		// Account 6 "pool_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, true, false))
		// Account 7 "coin_pnl_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinPnlTokenAccountAccount, true, false))
		// Account 8 "pc_pnl_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(pcPnlTokenAccountAccount, true, false))
		// Account 9 "pnl_owner_account": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(pnlOwnerAccountAccount, false, true))
		// Account 10 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 11 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 12 "serum_market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, true, false))
		// Account 13 "serum_event_queue": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQueueAccount, false, false))
		// Account 14 "serum_coin_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumCoinVaultAccountAccount, true, false))
		// Account 15 "serum_pc_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumPcVaultAccountAccount, true, false))
		// Account 16 "serum_vault_signer": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumVaultSignerAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "withdraw_srm" instruction.
func NewWithdrawSrmInstruction(
	// Params:
	amountParam uint64,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammOwnerAccountAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	srmTokenAccount solanago.PublicKey,
	destSrmTokenAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_WithdrawSrm[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "amm": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, false, false))
		// Account 2 "amm_owner_account": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOwnerAccountAccount, false, true))
		// Account 3 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 4 "srm_token": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(srmTokenAccount, true, false))
		// Account 5 "dest_srm_token": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destSrmTokenAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_base_in" instruction.
func NewSwapBaseInInstruction(
	// Params:
	amountInParam uint64,
	minimumAmountOutParam uint64,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	serumBidsAccount solanago.PublicKey,
	serumAsksAccount solanago.PublicKey,
	serumEventQueueAccount solanago.PublicKey,
	serumCoinVaultAccountAccount solanago.PublicKey,
	serumPcVaultAccountAccount solanago.PublicKey,
	serumVaultSignerAccount solanago.PublicKey,
	uerSourceTokenAccountAccount solanago.PublicKey,
	uerDestinationTokenAccountAccount solanago.PublicKey,
	userSourceOwnerAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.

	err := enc__.WriteBytes(Instruction_SwapBaseIn[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountInParam`:
		err = enc__.Encode(amountInParam)
		if err != nil {
			return nil, errors.NewField("amountInParam", err)
		}
		// Serialize `minimumAmountOutParam`:
		err = enc__.Encode(minimumAmountOutParam)
		if err != nil {
			return nil, errors.NewField("minimumAmountOutParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 2 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 3 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 4 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 5 "pool_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, true, false))
		// Account 6 "pool_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, true, false))
		// Account 7 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 8 "serum_market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, true, false))
		// Account 9 "serum_bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumBidsAccount, true, false))
		// Account 10 "serum_asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumAsksAccount, true, false))
		// Account 11 "serum_event_queue": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQueueAccount, true, false))
		// Account 12 "serum_coin_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumCoinVaultAccountAccount, true, false))
		// Account 13 "serum_pc_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumPcVaultAccountAccount, true, false))
		// Account 14 "serum_vault_signer": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumVaultSignerAccount, false, false))
		// Account 15 "uer_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(uerSourceTokenAccountAccount, true, false))
		// Account 16 "uer_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(uerDestinationTokenAccountAccount, true, false))
		// Account 17 "user_source_owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userSourceOwnerAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "pre_initialize" instruction.
func NewPreInitializeInstruction(
	// Params:
	nonceParam uint8,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	poolWithdrawQueueAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	lpMintAddressAccount solanago.PublicKey,
	coinMintAddressAccount solanago.PublicKey,
	pcMintAddressAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	poolTempLpTokenAccountAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	userWalletAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_PreInitialize[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `nonceParam`:
		err = enc__.Encode(nonceParam)
		if err != nil {
			return nil, errors.NewField("nonceParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 2 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
		// Account 3 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 4 "pool_withdraw_queue": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolWithdrawQueueAccount, true, false))
		// Account 5 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 6 "lp_mint_address": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAddressAccount, true, false))
		// Account 7 "coin_mint_address": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinMintAddressAccount, false, false))
		// Account 8 "pc_mint_address": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(pcMintAddressAccount, false, false))
		// Account 9 "pool_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, true, false))
		// Account 10 "pool_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, true, false))
		// Account 11 "pool_temp_lp_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolTempLpTokenAccountAccount, true, false))
		// Account 12 "serum_market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, false, false))
		// Account 13 "user_wallet": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userWalletAccount, true, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_base_out" instruction.
func NewSwapBaseOutInstruction(
	// Params:
	maxAmountInParam uint64,
	amountOutParam uint64,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	serumBidsAccount solanago.PublicKey,
	serumAsksAccount solanago.PublicKey,
	serumEventQueueAccount solanago.PublicKey,
	serumCoinVaultAccountAccount solanago.PublicKey,
	serumPcVaultAccountAccount solanago.PublicKey,
	serumVaultSignerAccount solanago.PublicKey,
	uerSourceTokenAccountAccount solanago.PublicKey,
	uerDestinationTokenAccountAccount solanago.PublicKey,
	userSourceOwnerAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapBaseOut[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `maxAmountInParam`:
		err = enc__.Encode(maxAmountInParam)
		if err != nil {
			return nil, errors.NewField("maxAmountInParam", err)
		}
		// Serialize `amountOutParam`:
		err = enc__.Encode(amountOutParam)
		if err != nil {
			return nil, errors.NewField("amountOutParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "amm": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, true, false))
		// Account 2 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 3 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 4 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 5 "pool_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, true, false))
		// Account 6 "pool_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, true, false))
		// Account 7 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 8 "serum_market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, true, false))
		// Account 9 "serum_bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumBidsAccount, true, false))
		// Account 10 "serum_asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumAsksAccount, true, false))
		// Account 11 "serum_event_queue": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQueueAccount, true, false))
		// Account 12 "serum_coin_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumCoinVaultAccountAccount, true, false))
		// Account 13 "serum_pc_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumPcVaultAccountAccount, true, false))
		// Account 14 "serum_vault_signer": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumVaultSignerAccount, false, false))
		// Account 15 "uer_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(uerSourceTokenAccountAccount, true, false))
		// Account 16 "uer_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(uerDestinationTokenAccountAccount, true, false))
		// Account 17 "user_source_owner": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userSourceOwnerAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "simulate_info" instruction.
func NewSimulateInfoInstruction(
	// Params:
	paramParam uint8,
	swapBaseInValueParam *SwapInstructionBaseIn,
	swapBaseOutValueParam *SwapInstructionBaseOut,

	// Accounts:
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	lpMintAddressAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	serumEventQueueAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SimulateInfo[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramParam`:
		err = enc__.Encode(paramParam)
		if err != nil {
			return nil, errors.NewField("paramParam", err)
		}
		// Serialize `swapBaseInValueParam` (optional):
		{
			if swapBaseInValueParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("swapBaseInValueParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("swapBaseInValueParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(swapBaseInValueParam)
				if err != nil {
					return nil, errors.NewField("swapBaseInValueParam", err)
				}
			}
		}
		// Serialize `swapBaseOutValueParam` (optional):
		{
			if swapBaseOutValueParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("swapBaseOutValueParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("swapBaseOutValueParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(swapBaseOutValueParam)
				if err != nil {
					return nil, errors.NewField("swapBaseOutValueParam", err)
				}
			}
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "amm": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, false, false))
		// Account 1 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 2 "amm_open_orders": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, false, false))
		// Account 3 "pool_coin_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, false, false))
		// Account 4 "pool_pc_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, false, false))
		// Account 5 "lp_mint_address": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAddressAccount, false, false))
		// Account 6 "serum_market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, false, false))
		// Account 7 "serum_event_queue": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQueueAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "admin_cancel_orders" instruction.
func NewAdminCancelOrdersInstruction(
	// Params:
	limitParam uint16,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	ammAccount solanago.PublicKey,
	ammAuthorityAccount solanago.PublicKey,
	ammOpenOrdersAccount solanago.PublicKey,
	ammTargetOrdersAccount solanago.PublicKey,
	poolCoinTokenAccountAccount solanago.PublicKey,
	poolPcTokenAccountAccount solanago.PublicKey,
	ammOwnerAccountAccount solanago.PublicKey,
	ammConfigAccount solanago.PublicKey,
	serumProgramAccount solanago.PublicKey,
	serumMarketAccount solanago.PublicKey,
	serumCoinVaultAccountAccount solanago.PublicKey,
	serumPcVaultAccountAccount solanago.PublicKey,
	serumVaultSignerAccount solanago.PublicKey,
	serumEventQAccount solanago.PublicKey,
	serumBidsAccount solanago.PublicKey,
	serumAsksAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_AdminCancelOrders[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `limitParam`:
		err = enc__.Encode(limitParam)
		if err != nil {
			return nil, errors.NewField("limitParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "amm": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAccount, false, false))
		// Account 2 "amm_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammAuthorityAccount, false, false))
		// Account 3 "amm_open_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOpenOrdersAccount, true, false))
		// Account 4 "amm_target_orders": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammTargetOrdersAccount, true, false))
		// Account 5 "pool_coin_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolCoinTokenAccountAccount, true, false))
		// Account 6 "pool_pc_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolPcTokenAccountAccount, true, false))
		// Account 7 "amm_owner_account": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammOwnerAccountAccount, false, true))
		// Account 8 "amm_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammConfigAccount, true, false))
		// Account 9 "serum_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumProgramAccount, false, false))
		// Account 10 "serum_market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumMarketAccount, true, false))
		// Account 11 "serum_coin_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumCoinVaultAccountAccount, true, false))
		// Account 12 "serum_pc_vault_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumPcVaultAccountAccount, true, false))
		// Account 13 "serum_vault_signer": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumVaultSignerAccount, false, false))
		// Account 14 "serum_event_q": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumEventQAccount, true, false))
		// Account 15 "serum_bids": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumBidsAccount, true, false))
		// Account 16 "serum_asks": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(serumAsksAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "create_config_account" instruction.
func NewCreateConfigAccountInstruction(
	adminAccount solanago.PublicKey,
	ammConfigAccount solanago.PublicKey,
	ownerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, true, true))
		// Account 1 "amm_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammConfigAccount, true, false))
		// Account 2 "owner": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, false))
		// Account 3 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 4 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "update_config_account" instruction.
func NewUpdateConfigAccountInstruction(
	// Params:
	paramParam uint8,
	ownerParam solanago.PublicKey,

	// Accounts:
	adminAccount solanago.PublicKey,
	ammConfigAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_UpdateConfigAccount[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramParam`:
		err = enc__.Encode(paramParam)
		if err != nil {
			return nil, errors.NewField("paramParam", err)
		}
		// Serialize `ownerParam`:
		err = enc__.Encode(ownerParam)
		if err != nil {
			return nil, errors.NewField("ownerParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
		// Account 1 "amm_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammConfigAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
