// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package raydium_amm

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8")

//var ProgramID = solanago.MustPublicKeyFromBase58("DRaya7Kj3aMWQSy19kSjvmuwq9docCHofyP9kanQGaav")
