// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package raydium_amm

import (
	"bytes"
	"fmt"

	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type WithdrawDestToken struct {
	WithdrawAmount uint64             `json:"withdrawAmount"`
	CoinAmount     uint64             `json:"coinAmount"`
	PcAmount       uint64             `json:"pcAmount"`
	DestTokenCoin  solanago.PublicKey `json:"destTokenCoin"`
	DestTokenPc    solanago.PublicKey `json:"destTokenPc"`
}

func (obj WithdrawDestToken) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `WithdrawAmount`:
	err = encoder.Encode(obj.WithdrawAmount)
	if err != nil {
		return errors.NewField("WithdrawAmount", err)
	}
	// Serialize `CoinAmount`:
	err = encoder.Encode(obj.CoinAmount)
	if err != nil {
		return errors.NewField("CoinAmount", err)
	}
	// Serialize `PcAmount`:
	err = encoder.Encode(obj.PcAmount)
	if err != nil {
		return errors.NewField("PcAmount", err)
	}
	// Serialize `DestTokenCoin`:
	err = encoder.Encode(obj.DestTokenCoin)
	if err != nil {
		return errors.NewField("DestTokenCoin", err)
	}
	// Serialize `DestTokenPc`:
	err = encoder.Encode(obj.DestTokenPc)
	if err != nil {
		return errors.NewField("DestTokenPc", err)
	}
	return nil
}

func (obj WithdrawDestToken) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WithdrawDestToken: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WithdrawDestToken) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `WithdrawAmount`:
	err = decoder.Decode(&obj.WithdrawAmount)
	if err != nil {
		return errors.NewField("WithdrawAmount", err)
	}
	// Deserialize `CoinAmount`:
	err = decoder.Decode(&obj.CoinAmount)
	if err != nil {
		return errors.NewField("CoinAmount", err)
	}
	// Deserialize `PcAmount`:
	err = decoder.Decode(&obj.PcAmount)
	if err != nil {
		return errors.NewField("PcAmount", err)
	}
	// Deserialize `DestTokenCoin`:
	err = decoder.Decode(&obj.DestTokenCoin)
	if err != nil {
		return errors.NewField("DestTokenCoin", err)
	}
	// Deserialize `DestTokenPc`:
	err = decoder.Decode(&obj.DestTokenPc)
	if err != nil {
		return errors.NewField("DestTokenPc", err)
	}
	return nil
}

func (obj *WithdrawDestToken) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WithdrawDestToken: %w", err)
	}
	return nil
}

func UnmarshalWithdrawDestToken(buf []byte) (*WithdrawDestToken, error) {
	obj := new(WithdrawDestToken)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type WithdrawQueue struct {
	Owner [4]uint64             `json:"owner"`
	Head  uint64                `json:"head"`
	Count uint64                `json:"count"`
	Buf   [64]WithdrawDestToken `json:"buf"`
}

func (obj WithdrawQueue) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `Head`:
	err = encoder.Encode(obj.Head)
	if err != nil {
		return errors.NewField("Head", err)
	}
	// Serialize `Count`:
	err = encoder.Encode(obj.Count)
	if err != nil {
		return errors.NewField("Count", err)
	}
	// Serialize `Buf`:
	err = encoder.Encode(obj.Buf)
	if err != nil {
		return errors.NewField("Buf", err)
	}
	return nil
}

func (obj WithdrawQueue) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WithdrawQueue: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WithdrawQueue) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `Head`:
	err = decoder.Decode(&obj.Head)
	if err != nil {
		return errors.NewField("Head", err)
	}
	// Deserialize `Count`:
	err = decoder.Decode(&obj.Count)
	if err != nil {
		return errors.NewField("Count", err)
	}
	// Deserialize `Buf`:
	err = decoder.Decode(&obj.Buf)
	if err != nil {
		return errors.NewField("Buf", err)
	}
	return nil
}

func (obj *WithdrawQueue) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WithdrawQueue: %w", err)
	}
	return nil
}

func UnmarshalWithdrawQueue(buf []byte) (*WithdrawQueue, error) {
	obj := new(WithdrawQueue)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TargetOrder struct {
	Price uint64 `json:"price"`
	Vol   uint64 `json:"vol"`
}

func (obj TargetOrder) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Price`:
	err = encoder.Encode(obj.Price)
	if err != nil {
		return errors.NewField("Price", err)
	}
	// Serialize `Vol`:
	err = encoder.Encode(obj.Vol)
	if err != nil {
		return errors.NewField("Vol", err)
	}
	return nil
}

func (obj TargetOrder) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TargetOrder: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TargetOrder) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Price`:
	err = decoder.Decode(&obj.Price)
	if err != nil {
		return errors.NewField("Price", err)
	}
	// Deserialize `Vol`:
	err = decoder.Decode(&obj.Vol)
	if err != nil {
		return errors.NewField("Vol", err)
	}
	return nil
}

func (obj *TargetOrder) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TargetOrder: %w", err)
	}
	return nil
}

func UnmarshalTargetOrder(buf []byte) (*TargetOrder, error) {
	obj := new(TargetOrder)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type OutPutData struct {
	NeedTakePnlCoin     uint64         `json:"needTakePnlCoin"`
	NeedTakePnlPc       uint64         `json:"needTakePnlPc"`
	TotalPnlPc          uint64         `json:"totalPnlPc"`
	TotalPnlCoin        uint64         `json:"totalPnlCoin"`
	PoolOpenTime        uint64         `json:"poolOpenTime"`
	PunishPcAmount      uint64         `json:"punishPcAmount"`
	PunishCoinAmount    uint64         `json:"punishCoinAmount"`
	OrderbookToInitTime uint64         `json:"orderbookToInitTime"`
	SwapCoinInAmount    binary.Uint128 `json:"swapCoinInAmount"`
	SwapPcOutAmount     binary.Uint128 `json:"swapPcOutAmount"`
	SwapTakePcFee       uint64         `json:"swapTakePcFee"`
	SwapPcInAmount      binary.Uint128 `json:"swapPcInAmount"`
	SwapCoinOutAmount   binary.Uint128 `json:"swapCoinOutAmount"`
	SwapTakeCoinFee     uint64         `json:"swapTakeCoinFee"`
}

func (obj OutPutData) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `NeedTakePnlCoin`:
	err = encoder.Encode(obj.NeedTakePnlCoin)
	if err != nil {
		return errors.NewField("NeedTakePnlCoin", err)
	}
	// Serialize `NeedTakePnlPc`:
	err = encoder.Encode(obj.NeedTakePnlPc)
	if err != nil {
		return errors.NewField("NeedTakePnlPc", err)
	}
	// Serialize `TotalPnlPc`:
	err = encoder.Encode(obj.TotalPnlPc)
	if err != nil {
		return errors.NewField("TotalPnlPc", err)
	}
	// Serialize `TotalPnlCoin`:
	err = encoder.Encode(obj.TotalPnlCoin)
	if err != nil {
		return errors.NewField("TotalPnlCoin", err)
	}
	// Serialize `PoolOpenTime`:
	err = encoder.Encode(obj.PoolOpenTime)
	if err != nil {
		return errors.NewField("PoolOpenTime", err)
	}
	// Serialize `PunishPcAmount`:
	err = encoder.Encode(obj.PunishPcAmount)
	if err != nil {
		return errors.NewField("PunishPcAmount", err)
	}
	// Serialize `PunishCoinAmount`:
	err = encoder.Encode(obj.PunishCoinAmount)
	if err != nil {
		return errors.NewField("PunishCoinAmount", err)
	}
	// Serialize `OrderbookToInitTime`:
	err = encoder.Encode(obj.OrderbookToInitTime)
	if err != nil {
		return errors.NewField("OrderbookToInitTime", err)
	}
	// Serialize `SwapCoinInAmount`:
	err = encoder.Encode(obj.SwapCoinInAmount)
	if err != nil {
		return errors.NewField("SwapCoinInAmount", err)
	}
	// Serialize `SwapPcOutAmount`:
	err = encoder.Encode(obj.SwapPcOutAmount)
	if err != nil {
		return errors.NewField("SwapPcOutAmount", err)
	}
	// Serialize `SwapTakePcFee`:
	err = encoder.Encode(obj.SwapTakePcFee)
	if err != nil {
		return errors.NewField("SwapTakePcFee", err)
	}
	// Serialize `SwapPcInAmount`:
	err = encoder.Encode(obj.SwapPcInAmount)
	if err != nil {
		return errors.NewField("SwapPcInAmount", err)
	}
	// Serialize `SwapCoinOutAmount`:
	err = encoder.Encode(obj.SwapCoinOutAmount)
	if err != nil {
		return errors.NewField("SwapCoinOutAmount", err)
	}
	// Serialize `SwapTakeCoinFee`:
	err = encoder.Encode(obj.SwapTakeCoinFee)
	if err != nil {
		return errors.NewField("SwapTakeCoinFee", err)
	}
	return nil
}

func (obj OutPutData) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding OutPutData: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *OutPutData) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `NeedTakePnlCoin`:
	err = decoder.Decode(&obj.NeedTakePnlCoin)
	if err != nil {
		return errors.NewField("NeedTakePnlCoin", err)
	}
	// Deserialize `NeedTakePnlPc`:
	err = decoder.Decode(&obj.NeedTakePnlPc)
	if err != nil {
		return errors.NewField("NeedTakePnlPc", err)
	}
	// Deserialize `TotalPnlPc`:
	err = decoder.Decode(&obj.TotalPnlPc)
	if err != nil {
		return errors.NewField("TotalPnlPc", err)
	}
	// Deserialize `TotalPnlCoin`:
	err = decoder.Decode(&obj.TotalPnlCoin)
	if err != nil {
		return errors.NewField("TotalPnlCoin", err)
	}
	// Deserialize `PoolOpenTime`:
	err = decoder.Decode(&obj.PoolOpenTime)
	if err != nil {
		return errors.NewField("PoolOpenTime", err)
	}
	// Deserialize `PunishPcAmount`:
	err = decoder.Decode(&obj.PunishPcAmount)
	if err != nil {
		return errors.NewField("PunishPcAmount", err)
	}
	// Deserialize `PunishCoinAmount`:
	err = decoder.Decode(&obj.PunishCoinAmount)
	if err != nil {
		return errors.NewField("PunishCoinAmount", err)
	}
	// Deserialize `OrderbookToInitTime`:
	err = decoder.Decode(&obj.OrderbookToInitTime)
	if err != nil {
		return errors.NewField("OrderbookToInitTime", err)
	}
	// Deserialize `SwapCoinInAmount`:
	err = decoder.Decode(&obj.SwapCoinInAmount)
	if err != nil {
		return errors.NewField("SwapCoinInAmount", err)
	}
	// Deserialize `SwapPcOutAmount`:
	err = decoder.Decode(&obj.SwapPcOutAmount)
	if err != nil {
		return errors.NewField("SwapPcOutAmount", err)
	}
	// Deserialize `SwapTakePcFee`:
	err = decoder.Decode(&obj.SwapTakePcFee)
	if err != nil {
		return errors.NewField("SwapTakePcFee", err)
	}
	// Deserialize `SwapPcInAmount`:
	err = decoder.Decode(&obj.SwapPcInAmount)
	if err != nil {
		return errors.NewField("SwapPcInAmount", err)
	}
	// Deserialize `SwapCoinOutAmount`:
	err = decoder.Decode(&obj.SwapCoinOutAmount)
	if err != nil {
		return errors.NewField("SwapCoinOutAmount", err)
	}
	// Deserialize `SwapTakeCoinFee`:
	err = decoder.Decode(&obj.SwapTakeCoinFee)
	if err != nil {
		return errors.NewField("SwapTakeCoinFee", err)
	}
	return nil
}

func (obj *OutPutData) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling OutPutData: %w", err)
	}
	return nil
}

func UnmarshalOutPutData(buf []byte) (*OutPutData, error) {
	obj := new(OutPutData)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type AmmConfig struct {
	PnlOwner    solanago.PublicKey `json:"pnlOwner"`
	CancelOwner solanago.PublicKey `json:"cancelOwner"`
	Pending1    [28]uint64         `json:"pending1"`
	Pending2    [32]uint64         `json:"pending2"`
}

func (obj AmmConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PnlOwner`:
	err = encoder.Encode(obj.PnlOwner)
	if err != nil {
		return errors.NewField("PnlOwner", err)
	}
	// Serialize `CancelOwner`:
	err = encoder.Encode(obj.CancelOwner)
	if err != nil {
		return errors.NewField("CancelOwner", err)
	}
	// Serialize `Pending1`:
	err = encoder.Encode(obj.Pending1)
	if err != nil {
		return errors.NewField("Pending1", err)
	}
	// Serialize `Pending2`:
	err = encoder.Encode(obj.Pending2)
	if err != nil {
		return errors.NewField("Pending2", err)
	}
	return nil
}

func (obj AmmConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AmmConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AmmConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PnlOwner`:
	err = decoder.Decode(&obj.PnlOwner)
	if err != nil {
		return errors.NewField("PnlOwner", err)
	}
	// Deserialize `CancelOwner`:
	err = decoder.Decode(&obj.CancelOwner)
	if err != nil {
		return errors.NewField("CancelOwner", err)
	}
	// Deserialize `Pending1`:
	err = decoder.Decode(&obj.Pending1)
	if err != nil {
		return errors.NewField("Pending1", err)
	}
	// Deserialize `Pending2`:
	err = decoder.Decode(&obj.Pending2)
	if err != nil {
		return errors.NewField("Pending2", err)
	}
	return nil
}

func (obj *AmmConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AmmConfig: %w", err)
	}
	return nil
}

func UnmarshalAmmConfig(buf []byte) (*AmmConfig, error) {
	obj := new(AmmConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type LastOrderDistance struct {
	LastOrderNumerator   uint64 `json:"lastOrderNumerator"`
	LastOrderDenominator uint64 `json:"lastOrderDenominator"`
}

func (obj LastOrderDistance) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `LastOrderNumerator`:
	err = encoder.Encode(obj.LastOrderNumerator)
	if err != nil {
		return errors.NewField("LastOrderNumerator", err)
	}
	// Serialize `LastOrderDenominator`:
	err = encoder.Encode(obj.LastOrderDenominator)
	if err != nil {
		return errors.NewField("LastOrderDenominator", err)
	}
	return nil
}

func (obj LastOrderDistance) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding LastOrderDistance: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *LastOrderDistance) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `LastOrderNumerator`:
	err = decoder.Decode(&obj.LastOrderNumerator)
	if err != nil {
		return errors.NewField("LastOrderNumerator", err)
	}
	// Deserialize `LastOrderDenominator`:
	err = decoder.Decode(&obj.LastOrderDenominator)
	if err != nil {
		return errors.NewField("LastOrderDenominator", err)
	}
	return nil
}

func (obj *LastOrderDistance) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling LastOrderDistance: %w", err)
	}
	return nil
}

func UnmarshalLastOrderDistance(buf []byte) (*LastOrderDistance, error) {
	obj := new(LastOrderDistance)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type NeedTake struct {
	NeedTakePc   uint64 `json:"needTakePc"`
	NeedTakeCoin uint64 `json:"needTakeCoin"`
}

func (obj NeedTake) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `NeedTakePc`:
	err = encoder.Encode(obj.NeedTakePc)
	if err != nil {
		return errors.NewField("NeedTakePc", err)
	}
	// Serialize `NeedTakeCoin`:
	err = encoder.Encode(obj.NeedTakeCoin)
	if err != nil {
		return errors.NewField("NeedTakeCoin", err)
	}
	return nil
}

func (obj NeedTake) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding NeedTake: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *NeedTake) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `NeedTakePc`:
	err = decoder.Decode(&obj.NeedTakePc)
	if err != nil {
		return errors.NewField("NeedTakePc", err)
	}
	// Deserialize `NeedTakeCoin`:
	err = decoder.Decode(&obj.NeedTakeCoin)
	if err != nil {
		return errors.NewField("NeedTakeCoin", err)
	}
	return nil
}

func (obj *NeedTake) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling NeedTake: %w", err)
	}
	return nil
}

func UnmarshalNeedTake(buf []byte) (*NeedTake, error) {
	obj := new(NeedTake)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SwapInstructionBaseIn struct {
	AmountIn         uint64 `json:"amountIn"`
	MinimumAmountOut uint64 `json:"minimumAmountOut"`
}

func (obj SwapInstructionBaseIn) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `AmountIn`:
	err = encoder.Encode(obj.AmountIn)
	if err != nil {
		return errors.NewField("AmountIn", err)
	}
	// Serialize `MinimumAmountOut`:
	err = encoder.Encode(obj.MinimumAmountOut)
	if err != nil {
		return errors.NewField("MinimumAmountOut", err)
	}
	return nil
}

func (obj SwapInstructionBaseIn) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SwapInstructionBaseIn: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SwapInstructionBaseIn) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `AmountIn`:
	err = decoder.Decode(&obj.AmountIn)
	if err != nil {
		return errors.NewField("AmountIn", err)
	}
	// Deserialize `MinimumAmountOut`:
	err = decoder.Decode(&obj.MinimumAmountOut)
	if err != nil {
		return errors.NewField("MinimumAmountOut", err)
	}
	return nil
}

func (obj *SwapInstructionBaseIn) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SwapInstructionBaseIn: %w", err)
	}
	return nil
}

func UnmarshalSwapInstructionBaseIn(buf []byte) (*SwapInstructionBaseIn, error) {
	obj := new(SwapInstructionBaseIn)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SwapInstructionBaseOut struct {
	MaxAmountIn uint64 `json:"maxAmountIn"`
	AmountOut   uint64 `json:"amountOut"`
}

func (obj SwapInstructionBaseOut) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MaxAmountIn`:
	err = encoder.Encode(obj.MaxAmountIn)
	if err != nil {
		return errors.NewField("MaxAmountIn", err)
	}
	// Serialize `AmountOut`:
	err = encoder.Encode(obj.AmountOut)
	if err != nil {
		return errors.NewField("AmountOut", err)
	}
	return nil
}

func (obj SwapInstructionBaseOut) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SwapInstructionBaseOut: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SwapInstructionBaseOut) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MaxAmountIn`:
	err = decoder.Decode(&obj.MaxAmountIn)
	if err != nil {
		return errors.NewField("MaxAmountIn", err)
	}
	// Deserialize `AmountOut`:
	err = decoder.Decode(&obj.AmountOut)
	if err != nil {
		return errors.NewField("AmountOut", err)
	}
	return nil
}

func (obj *SwapInstructionBaseOut) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SwapInstructionBaseOut: %w", err)
	}
	return nil
}

func UnmarshalSwapInstructionBaseOut(buf []byte) (*SwapInstructionBaseOut, error) {
	obj := new(SwapInstructionBaseOut)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TargetOrders struct {
	Owner                [4]uint64       `json:"owner"`
	BuyOrders            [50]TargetOrder `json:"buyOrders"`
	Padding1             [8]uint64       `json:"padding1"`
	TargetX              binary.Uint128  `json:"targetX"`
	TargetY              binary.Uint128  `json:"targetY"`
	PlanXBuy             binary.Uint128  `json:"planXBuy"`
	PlanYBuy             binary.Uint128  `json:"planYBuy"`
	PlanXSell            binary.Uint128  `json:"planXSell"`
	PlanYSell            binary.Uint128  `json:"planYSell"`
	PlacedX              binary.Uint128  `json:"placedX"`
	PlacedY              binary.Uint128  `json:"placedY"`
	CalcPnlX             binary.Uint128  `json:"calcPnlX"`
	CalcPnlY             binary.Uint128  `json:"calcPnlY"`
	SellOrders           [50]TargetOrder `json:"sellOrders"`
	Padding2             [6]uint64       `json:"padding2"`
	ReplaceBuyClientId   [10]uint64      `json:"replaceBuyClientId"`
	ReplaceSellClientId  [10]uint64      `json:"replaceSellClientId"`
	LastOrderNumerator   uint64          `json:"lastOrderNumerator"`
	LastOrderDenominator uint64          `json:"lastOrderDenominator"`
	PlanOrdersCur        uint64          `json:"planOrdersCur"`
	PlaceOrdersCur       uint64          `json:"placeOrdersCur"`
	ValidBuyOrderNum     uint64          `json:"validBuyOrderNum"`
	ValidSellOrderNum    uint64          `json:"validSellOrderNum"`
	Padding3             [10]uint64      `json:"padding3"`
	FreeSlotBits         binary.Uint128  `json:"freeSlotBits"`
}

func (obj TargetOrders) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `BuyOrders`:
	err = encoder.Encode(obj.BuyOrders)
	if err != nil {
		return errors.NewField("BuyOrders", err)
	}
	// Serialize `Padding1`:
	err = encoder.Encode(obj.Padding1)
	if err != nil {
		return errors.NewField("Padding1", err)
	}
	// Serialize `TargetX`:
	err = encoder.Encode(obj.TargetX)
	if err != nil {
		return errors.NewField("TargetX", err)
	}
	// Serialize `TargetY`:
	err = encoder.Encode(obj.TargetY)
	if err != nil {
		return errors.NewField("TargetY", err)
	}
	// Serialize `PlanXBuy`:
	err = encoder.Encode(obj.PlanXBuy)
	if err != nil {
		return errors.NewField("PlanXBuy", err)
	}
	// Serialize `PlanYBuy`:
	err = encoder.Encode(obj.PlanYBuy)
	if err != nil {
		return errors.NewField("PlanYBuy", err)
	}
	// Serialize `PlanXSell`:
	err = encoder.Encode(obj.PlanXSell)
	if err != nil {
		return errors.NewField("PlanXSell", err)
	}
	// Serialize `PlanYSell`:
	err = encoder.Encode(obj.PlanYSell)
	if err != nil {
		return errors.NewField("PlanYSell", err)
	}
	// Serialize `PlacedX`:
	err = encoder.Encode(obj.PlacedX)
	if err != nil {
		return errors.NewField("PlacedX", err)
	}
	// Serialize `PlacedY`:
	err = encoder.Encode(obj.PlacedY)
	if err != nil {
		return errors.NewField("PlacedY", err)
	}
	// Serialize `CalcPnlX`:
	err = encoder.Encode(obj.CalcPnlX)
	if err != nil {
		return errors.NewField("CalcPnlX", err)
	}
	// Serialize `CalcPnlY`:
	err = encoder.Encode(obj.CalcPnlY)
	if err != nil {
		return errors.NewField("CalcPnlY", err)
	}
	// Serialize `SellOrders`:
	err = encoder.Encode(obj.SellOrders)
	if err != nil {
		return errors.NewField("SellOrders", err)
	}
	// Serialize `Padding2`:
	err = encoder.Encode(obj.Padding2)
	if err != nil {
		return errors.NewField("Padding2", err)
	}
	// Serialize `ReplaceBuyClientId`:
	err = encoder.Encode(obj.ReplaceBuyClientId)
	if err != nil {
		return errors.NewField("ReplaceBuyClientId", err)
	}
	// Serialize `ReplaceSellClientId`:
	err = encoder.Encode(obj.ReplaceSellClientId)
	if err != nil {
		return errors.NewField("ReplaceSellClientId", err)
	}
	// Serialize `LastOrderNumerator`:
	err = encoder.Encode(obj.LastOrderNumerator)
	if err != nil {
		return errors.NewField("LastOrderNumerator", err)
	}
	// Serialize `LastOrderDenominator`:
	err = encoder.Encode(obj.LastOrderDenominator)
	if err != nil {
		return errors.NewField("LastOrderDenominator", err)
	}
	// Serialize `PlanOrdersCur`:
	err = encoder.Encode(obj.PlanOrdersCur)
	if err != nil {
		return errors.NewField("PlanOrdersCur", err)
	}
	// Serialize `PlaceOrdersCur`:
	err = encoder.Encode(obj.PlaceOrdersCur)
	if err != nil {
		return errors.NewField("PlaceOrdersCur", err)
	}
	// Serialize `ValidBuyOrderNum`:
	err = encoder.Encode(obj.ValidBuyOrderNum)
	if err != nil {
		return errors.NewField("ValidBuyOrderNum", err)
	}
	// Serialize `ValidSellOrderNum`:
	err = encoder.Encode(obj.ValidSellOrderNum)
	if err != nil {
		return errors.NewField("ValidSellOrderNum", err)
	}
	// Serialize `Padding3`:
	err = encoder.Encode(obj.Padding3)
	if err != nil {
		return errors.NewField("Padding3", err)
	}
	// Serialize `FreeSlotBits`:
	err = encoder.Encode(obj.FreeSlotBits)
	if err != nil {
		return errors.NewField("FreeSlotBits", err)
	}
	return nil
}

func (obj TargetOrders) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TargetOrders: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TargetOrders) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `BuyOrders`:
	err = decoder.Decode(&obj.BuyOrders)
	if err != nil {
		return errors.NewField("BuyOrders", err)
	}
	// Deserialize `Padding1`:
	err = decoder.Decode(&obj.Padding1)
	if err != nil {
		return errors.NewField("Padding1", err)
	}
	// Deserialize `TargetX`:
	err = decoder.Decode(&obj.TargetX)
	if err != nil {
		return errors.NewField("TargetX", err)
	}
	// Deserialize `TargetY`:
	err = decoder.Decode(&obj.TargetY)
	if err != nil {
		return errors.NewField("TargetY", err)
	}
	// Deserialize `PlanXBuy`:
	err = decoder.Decode(&obj.PlanXBuy)
	if err != nil {
		return errors.NewField("PlanXBuy", err)
	}
	// Deserialize `PlanYBuy`:
	err = decoder.Decode(&obj.PlanYBuy)
	if err != nil {
		return errors.NewField("PlanYBuy", err)
	}
	// Deserialize `PlanXSell`:
	err = decoder.Decode(&obj.PlanXSell)
	if err != nil {
		return errors.NewField("PlanXSell", err)
	}
	// Deserialize `PlanYSell`:
	err = decoder.Decode(&obj.PlanYSell)
	if err != nil {
		return errors.NewField("PlanYSell", err)
	}
	// Deserialize `PlacedX`:
	err = decoder.Decode(&obj.PlacedX)
	if err != nil {
		return errors.NewField("PlacedX", err)
	}
	// Deserialize `PlacedY`:
	err = decoder.Decode(&obj.PlacedY)
	if err != nil {
		return errors.NewField("PlacedY", err)
	}
	// Deserialize `CalcPnlX`:
	err = decoder.Decode(&obj.CalcPnlX)
	if err != nil {
		return errors.NewField("CalcPnlX", err)
	}
	// Deserialize `CalcPnlY`:
	err = decoder.Decode(&obj.CalcPnlY)
	if err != nil {
		return errors.NewField("CalcPnlY", err)
	}
	// Deserialize `SellOrders`:
	err = decoder.Decode(&obj.SellOrders)
	if err != nil {
		return errors.NewField("SellOrders", err)
	}
	// Deserialize `Padding2`:
	err = decoder.Decode(&obj.Padding2)
	if err != nil {
		return errors.NewField("Padding2", err)
	}
	// Deserialize `ReplaceBuyClientId`:
	err = decoder.Decode(&obj.ReplaceBuyClientId)
	if err != nil {
		return errors.NewField("ReplaceBuyClientId", err)
	}
	// Deserialize `ReplaceSellClientId`:
	err = decoder.Decode(&obj.ReplaceSellClientId)
	if err != nil {
		return errors.NewField("ReplaceSellClientId", err)
	}
	// Deserialize `LastOrderNumerator`:
	err = decoder.Decode(&obj.LastOrderNumerator)
	if err != nil {
		return errors.NewField("LastOrderNumerator", err)
	}
	// Deserialize `LastOrderDenominator`:
	err = decoder.Decode(&obj.LastOrderDenominator)
	if err != nil {
		return errors.NewField("LastOrderDenominator", err)
	}
	// Deserialize `PlanOrdersCur`:
	err = decoder.Decode(&obj.PlanOrdersCur)
	if err != nil {
		return errors.NewField("PlanOrdersCur", err)
	}
	// Deserialize `PlaceOrdersCur`:
	err = decoder.Decode(&obj.PlaceOrdersCur)
	if err != nil {
		return errors.NewField("PlaceOrdersCur", err)
	}
	// Deserialize `ValidBuyOrderNum`:
	err = decoder.Decode(&obj.ValidBuyOrderNum)
	if err != nil {
		return errors.NewField("ValidBuyOrderNum", err)
	}
	// Deserialize `ValidSellOrderNum`:
	err = decoder.Decode(&obj.ValidSellOrderNum)
	if err != nil {
		return errors.NewField("ValidSellOrderNum", err)
	}
	// Deserialize `Padding3`:
	err = decoder.Decode(&obj.Padding3)
	if err != nil {
		return errors.NewField("Padding3", err)
	}
	// Deserialize `FreeSlotBits`:
	err = decoder.Decode(&obj.FreeSlotBits)
	if err != nil {
		return errors.NewField("FreeSlotBits", err)
	}
	return nil
}

func (obj *TargetOrders) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TargetOrders: %w", err)
	}
	return nil
}

func UnmarshalTargetOrders(buf []byte) (*TargetOrders, error) {
	obj := new(TargetOrders)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Fees struct {
	MinSeparateNumerator   uint64 `json:"minSeparateNumerator"`
	MinSeparateDenominator uint64 `json:"minSeparateDenominator"`
	TradeFeeNumerator      uint64 `json:"tradeFeeNumerator"`
	TradeFeeDenominator    uint64 `json:"tradeFeeDenominator"`
	PnlNumerator           uint64 `json:"pnlNumerator"`
	PnlDenominator         uint64 `json:"pnlDenominator"`
	SwapFeeNumerator       uint64 `json:"swapFeeNumerator"`
	SwapFeeDenominator     uint64 `json:"swapFeeDenominator"`
}

func (obj Fees) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MinSeparateNumerator`:
	err = encoder.Encode(obj.MinSeparateNumerator)
	if err != nil {
		return errors.NewField("MinSeparateNumerator", err)
	}
	// Serialize `MinSeparateDenominator`:
	err = encoder.Encode(obj.MinSeparateDenominator)
	if err != nil {
		return errors.NewField("MinSeparateDenominator", err)
	}
	// Serialize `TradeFeeNumerator`:
	err = encoder.Encode(obj.TradeFeeNumerator)
	if err != nil {
		return errors.NewField("TradeFeeNumerator", err)
	}
	// Serialize `TradeFeeDenominator`:
	err = encoder.Encode(obj.TradeFeeDenominator)
	if err != nil {
		return errors.NewField("TradeFeeDenominator", err)
	}
	// Serialize `PnlNumerator`:
	err = encoder.Encode(obj.PnlNumerator)
	if err != nil {
		return errors.NewField("PnlNumerator", err)
	}
	// Serialize `PnlDenominator`:
	err = encoder.Encode(obj.PnlDenominator)
	if err != nil {
		return errors.NewField("PnlDenominator", err)
	}
	// Serialize `SwapFeeNumerator`:
	err = encoder.Encode(obj.SwapFeeNumerator)
	if err != nil {
		return errors.NewField("SwapFeeNumerator", err)
	}
	// Serialize `SwapFeeDenominator`:
	err = encoder.Encode(obj.SwapFeeDenominator)
	if err != nil {
		return errors.NewField("SwapFeeDenominator", err)
	}
	return nil
}

func (obj Fees) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Fees: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Fees) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MinSeparateNumerator`:
	err = decoder.Decode(&obj.MinSeparateNumerator)
	if err != nil {
		return errors.NewField("MinSeparateNumerator", err)
	}
	// Deserialize `MinSeparateDenominator`:
	err = decoder.Decode(&obj.MinSeparateDenominator)
	if err != nil {
		return errors.NewField("MinSeparateDenominator", err)
	}
	// Deserialize `TradeFeeNumerator`:
	err = decoder.Decode(&obj.TradeFeeNumerator)
	if err != nil {
		return errors.NewField("TradeFeeNumerator", err)
	}
	// Deserialize `TradeFeeDenominator`:
	err = decoder.Decode(&obj.TradeFeeDenominator)
	if err != nil {
		return errors.NewField("TradeFeeDenominator", err)
	}
	// Deserialize `PnlNumerator`:
	err = decoder.Decode(&obj.PnlNumerator)
	if err != nil {
		return errors.NewField("PnlNumerator", err)
	}
	// Deserialize `PnlDenominator`:
	err = decoder.Decode(&obj.PnlDenominator)
	if err != nil {
		return errors.NewField("PnlDenominator", err)
	}
	// Deserialize `SwapFeeNumerator`:
	err = decoder.Decode(&obj.SwapFeeNumerator)
	if err != nil {
		return errors.NewField("SwapFeeNumerator", err)
	}
	// Deserialize `SwapFeeDenominator`:
	err = decoder.Decode(&obj.SwapFeeDenominator)
	if err != nil {
		return errors.NewField("SwapFeeDenominator", err)
	}
	return nil
}

func (obj *Fees) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Fees: %w", err)
	}
	return nil
}

func UnmarshalFees(buf []byte) (*Fees, error) {
	obj := new(Fees)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type AmmInfo struct {
	Status             uint64             `json:"status"`
	Nonce              uint64             `json:"nonce"`
	OrderNum           uint64             `json:"orderNum"`
	Depth              uint64             `json:"depth"`
	CoinDecimals       uint64             `json:"coinDecimals"`
	PcDecimals         uint64             `json:"pcDecimals"`
	State              uint64             `json:"state"`
	ResetFlag          uint64             `json:"resetFlag"`
	MinSize            uint64             `json:"minSize"`
	VolMaxCutRatio     uint64             `json:"volMaxCutRatio"`
	AmountWave         uint64             `json:"amountWave"`
	CoinLotSize        uint64             `json:"coinLotSize"`
	PcLotSize          uint64             `json:"pcLotSize"`
	MinPriceMultiplier uint64             `json:"minPriceMultiplier"`
	MaxPriceMultiplier uint64             `json:"maxPriceMultiplier"`
	SysDecimalValue    uint64             `json:"sysDecimalValue"`
	Fees               Fees               `json:"fees"`
	OutPut             OutPutData         `json:"outPut"`
	TokenCoin          solanago.PublicKey `json:"tokenCoin"`
	TokenPc            solanago.PublicKey `json:"tokenPc"`
	CoinMint           solanago.PublicKey `json:"coinMint"`
	PcMint             solanago.PublicKey `json:"pcMint"`
	LpMint             solanago.PublicKey `json:"lpMint"`
	OpenOrders         solanago.PublicKey `json:"openOrders"`
	Market             solanago.PublicKey `json:"market"`
	SerumDex           solanago.PublicKey `json:"serumDex"`
	TargetOrders       solanago.PublicKey `json:"targetOrders"`
	WithdrawQueue      solanago.PublicKey `json:"withdrawQueue"`
	TokenTempLp        solanago.PublicKey `json:"tokenTempLp"`
	AmmOwner           solanago.PublicKey `json:"ammOwner"`
	LpAmount           uint64             `json:"lpAmount"`
	ClientOrderId      uint64             `json:"clientOrderId"`
	Padding            [2]uint64          `json:"padding"`
}

func (obj AmmInfo) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Status`:
	err = encoder.Encode(obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Serialize `Nonce`:
	err = encoder.Encode(obj.Nonce)
	if err != nil {
		return errors.NewField("Nonce", err)
	}
	// Serialize `OrderNum`:
	err = encoder.Encode(obj.OrderNum)
	if err != nil {
		return errors.NewField("OrderNum", err)
	}
	// Serialize `Depth`:
	err = encoder.Encode(obj.Depth)
	if err != nil {
		return errors.NewField("Depth", err)
	}
	// Serialize `CoinDecimals`:
	err = encoder.Encode(obj.CoinDecimals)
	if err != nil {
		return errors.NewField("CoinDecimals", err)
	}
	// Serialize `PcDecimals`:
	err = encoder.Encode(obj.PcDecimals)
	if err != nil {
		return errors.NewField("PcDecimals", err)
	}
	// Serialize `State`:
	err = encoder.Encode(obj.State)
	if err != nil {
		return errors.NewField("State", err)
	}
	// Serialize `ResetFlag`:
	err = encoder.Encode(obj.ResetFlag)
	if err != nil {
		return errors.NewField("ResetFlag", err)
	}
	// Serialize `MinSize`:
	err = encoder.Encode(obj.MinSize)
	if err != nil {
		return errors.NewField("MinSize", err)
	}
	// Serialize `VolMaxCutRatio`:
	err = encoder.Encode(obj.VolMaxCutRatio)
	if err != nil {
		return errors.NewField("VolMaxCutRatio", err)
	}
	// Serialize `AmountWave`:
	err = encoder.Encode(obj.AmountWave)
	if err != nil {
		return errors.NewField("AmountWave", err)
	}
	// Serialize `CoinLotSize`:
	err = encoder.Encode(obj.CoinLotSize)
	if err != nil {
		return errors.NewField("CoinLotSize", err)
	}
	// Serialize `PcLotSize`:
	err = encoder.Encode(obj.PcLotSize)
	if err != nil {
		return errors.NewField("PcLotSize", err)
	}
	// Serialize `MinPriceMultiplier`:
	err = encoder.Encode(obj.MinPriceMultiplier)
	if err != nil {
		return errors.NewField("MinPriceMultiplier", err)
	}
	// Serialize `MaxPriceMultiplier`:
	err = encoder.Encode(obj.MaxPriceMultiplier)
	if err != nil {
		return errors.NewField("MaxPriceMultiplier", err)
	}
	// Serialize `SysDecimalValue`:
	err = encoder.Encode(obj.SysDecimalValue)
	if err != nil {
		return errors.NewField("SysDecimalValue", err)
	}
	// Serialize `Fees`:
	err = encoder.Encode(obj.Fees)
	if err != nil {
		return errors.NewField("Fees", err)
	}
	// Serialize `OutPut`:
	err = encoder.Encode(obj.OutPut)
	if err != nil {
		return errors.NewField("OutPut", err)
	}
	// Serialize `TokenCoin`:
	err = encoder.Encode(obj.TokenCoin)
	if err != nil {
		return errors.NewField("TokenCoin", err)
	}
	// Serialize `TokenPc`:
	err = encoder.Encode(obj.TokenPc)
	if err != nil {
		return errors.NewField("TokenPc", err)
	}
	// Serialize `CoinMint`:
	err = encoder.Encode(obj.CoinMint)
	if err != nil {
		return errors.NewField("CoinMint", err)
	}
	// Serialize `PcMint`:
	err = encoder.Encode(obj.PcMint)
	if err != nil {
		return errors.NewField("PcMint", err)
	}
	// Serialize `LpMint`:
	err = encoder.Encode(obj.LpMint)
	if err != nil {
		return errors.NewField("LpMint", err)
	}
	// Serialize `OpenOrders`:
	err = encoder.Encode(obj.OpenOrders)
	if err != nil {
		return errors.NewField("OpenOrders", err)
	}
	// Serialize `Market`:
	err = encoder.Encode(obj.Market)
	if err != nil {
		return errors.NewField("Market", err)
	}
	// Serialize `SerumDex`:
	err = encoder.Encode(obj.SerumDex)
	if err != nil {
		return errors.NewField("SerumDex", err)
	}
	// Serialize `TargetOrders`:
	err = encoder.Encode(obj.TargetOrders)
	if err != nil {
		return errors.NewField("TargetOrders", err)
	}
	// Serialize `WithdrawQueue`:
	err = encoder.Encode(obj.WithdrawQueue)
	if err != nil {
		return errors.NewField("WithdrawQueue", err)
	}
	// Serialize `TokenTempLp`:
	err = encoder.Encode(obj.TokenTempLp)
	if err != nil {
		return errors.NewField("TokenTempLp", err)
	}
	// Serialize `AmmOwner`:
	err = encoder.Encode(obj.AmmOwner)
	if err != nil {
		return errors.NewField("AmmOwner", err)
	}
	// Serialize `LpAmount`:
	err = encoder.Encode(obj.LpAmount)
	if err != nil {
		return errors.NewField("LpAmount", err)
	}
	// Serialize `ClientOrderId`:
	err = encoder.Encode(obj.ClientOrderId)
	if err != nil {
		return errors.NewField("ClientOrderId", err)
	}
	// Serialize `Padding`:
	err = encoder.Encode(obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj AmmInfo) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AmmInfo: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AmmInfo) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Status`:
	err = decoder.Decode(&obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Deserialize `Nonce`:
	err = decoder.Decode(&obj.Nonce)
	if err != nil {
		return errors.NewField("Nonce", err)
	}
	// Deserialize `OrderNum`:
	err = decoder.Decode(&obj.OrderNum)
	if err != nil {
		return errors.NewField("OrderNum", err)
	}
	// Deserialize `Depth`:
	err = decoder.Decode(&obj.Depth)
	if err != nil {
		return errors.NewField("Depth", err)
	}
	// Deserialize `CoinDecimals`:
	err = decoder.Decode(&obj.CoinDecimals)
	if err != nil {
		return errors.NewField("CoinDecimals", err)
	}
	// Deserialize `PcDecimals`:
	err = decoder.Decode(&obj.PcDecimals)
	if err != nil {
		return errors.NewField("PcDecimals", err)
	}
	// Deserialize `State`:
	err = decoder.Decode(&obj.State)
	if err != nil {
		return errors.NewField("State", err)
	}
	// Deserialize `ResetFlag`:
	err = decoder.Decode(&obj.ResetFlag)
	if err != nil {
		return errors.NewField("ResetFlag", err)
	}
	// Deserialize `MinSize`:
	err = decoder.Decode(&obj.MinSize)
	if err != nil {
		return errors.NewField("MinSize", err)
	}
	// Deserialize `VolMaxCutRatio`:
	err = decoder.Decode(&obj.VolMaxCutRatio)
	if err != nil {
		return errors.NewField("VolMaxCutRatio", err)
	}
	// Deserialize `AmountWave`:
	err = decoder.Decode(&obj.AmountWave)
	if err != nil {
		return errors.NewField("AmountWave", err)
	}
	// Deserialize `CoinLotSize`:
	err = decoder.Decode(&obj.CoinLotSize)
	if err != nil {
		return errors.NewField("CoinLotSize", err)
	}
	// Deserialize `PcLotSize`:
	err = decoder.Decode(&obj.PcLotSize)
	if err != nil {
		return errors.NewField("PcLotSize", err)
	}
	// Deserialize `MinPriceMultiplier`:
	err = decoder.Decode(&obj.MinPriceMultiplier)
	if err != nil {
		return errors.NewField("MinPriceMultiplier", err)
	}
	// Deserialize `MaxPriceMultiplier`:
	err = decoder.Decode(&obj.MaxPriceMultiplier)
	if err != nil {
		return errors.NewField("MaxPriceMultiplier", err)
	}
	// Deserialize `SysDecimalValue`:
	err = decoder.Decode(&obj.SysDecimalValue)
	if err != nil {
		return errors.NewField("SysDecimalValue", err)
	}
	// Deserialize `Fees`:
	err = decoder.Decode(&obj.Fees)
	if err != nil {
		return errors.NewField("Fees", err)
	}
	// Deserialize `OutPut`:
	err = decoder.Decode(&obj.OutPut)
	if err != nil {
		return errors.NewField("OutPut", err)
	}
	// Deserialize `TokenCoin`:
	err = decoder.Decode(&obj.TokenCoin)
	if err != nil {
		return errors.NewField("TokenCoin", err)
	}
	// Deserialize `TokenPc`:
	err = decoder.Decode(&obj.TokenPc)
	if err != nil {
		return errors.NewField("TokenPc", err)
	}
	// Deserialize `CoinMint`:
	err = decoder.Decode(&obj.CoinMint)
	if err != nil {
		return errors.NewField("CoinMint", err)
	}
	// Deserialize `PcMint`:
	err = decoder.Decode(&obj.PcMint)
	if err != nil {
		return errors.NewField("PcMint", err)
	}
	// Deserialize `LpMint`:
	err = decoder.Decode(&obj.LpMint)
	if err != nil {
		return errors.NewField("LpMint", err)
	}
	// Deserialize `OpenOrders`:
	err = decoder.Decode(&obj.OpenOrders)
	if err != nil {
		return errors.NewField("OpenOrders", err)
	}
	// Deserialize `Market`:
	err = decoder.Decode(&obj.Market)
	if err != nil {
		return errors.NewField("Market", err)
	}
	// Deserialize `SerumDex`:
	err = decoder.Decode(&obj.SerumDex)
	if err != nil {
		return errors.NewField("SerumDex", err)
	}
	// Deserialize `TargetOrders`:
	err = decoder.Decode(&obj.TargetOrders)
	if err != nil {
		return errors.NewField("TargetOrders", err)
	}
	// Deserialize `WithdrawQueue`:
	err = decoder.Decode(&obj.WithdrawQueue)
	if err != nil {
		return errors.NewField("WithdrawQueue", err)
	}
	// Deserialize `TokenTempLp`:
	err = decoder.Decode(&obj.TokenTempLp)
	if err != nil {
		return errors.NewField("TokenTempLp", err)
	}
	// Deserialize `AmmOwner`:
	err = decoder.Decode(&obj.AmmOwner)
	if err != nil {
		return errors.NewField("AmmOwner", err)
	}
	// Deserialize `LpAmount`:
	err = decoder.Decode(&obj.LpAmount)
	if err != nil {
		return errors.NewField("LpAmount", err)
	}
	// Deserialize `ClientOrderId`:
	err = decoder.Decode(&obj.ClientOrderId)
	if err != nil {
		return errors.NewField("ClientOrderId", err)
	}
	// Deserialize `Padding`:
	err = decoder.Decode(&obj.Padding)
	if err != nil {
		return errors.NewField("Padding", err)
	}
	return nil
}

func (obj *AmmInfo) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AmmInfo: %w", err)
	}
	return nil
}

func UnmarshalAmmInfo(buf []byte) (*AmmInfo, error) {
	obj := new(AmmInfo)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
